### ISSUE TITLE
Vertically resizable text areas

### ISSUE THREAD

**Issue by nicknytko** [inducer/relate#1019]
It would be nice if the text area element could either be vertically resizable, or if it automatically fills the page.  This could probably be done by a css property:

https://developer.mozilla.org/en-US/docs/Web/CSS/resize

My use case:

![image](https://github.com/inducer/relate/assets/1790491/6b5f6e89-e83f-4344-b57b-b06eb509be02)

it would be nice to have more room to edit text.

**Comment by inducer** [comment]
Totally agree. #1012 contains a switch to CodeMirror 6, which makes the editor as big as the text contained in it, instead of having it be independently scrollable. That should address the concern, I think (in addition to avoiding burning people's retinas at night).
