### ISSUE TITLE
Make permission bit to hide final flow result

### ISSUE THREAD

**Issue by inducer** [inducer/relate#103]

**Comment by inducer** [comment]
@lukeolson How soon do you need that?

**Comment by lukeolson** [comment]
now?   For an exam I don't want results known before some students even start.

**Comment by inducer** [comment]
As in, your exam starts today?

**Comment by lukeolson** [comment]
Sunday morning.

**Comment by inducer** [comment]
K, will do this afternoon. Something like `cannot_see_result` probably.

**Comment by inducer** [comment]
Fixed in 0c9c494d2168f.

http://documen.tician.de/relate/flow.html#course.constants.flow_permission.cannot_see_flow_result

Live on the UIUC instance.
