### ISSUE TITLE
poetry install stuck on Ubuntu 20.04 + machine

### ISSUE THREAD

**Issue by neychevr** [inducer/relate#1043]
If someone faces the issue when `poetry install` takes forever, keyring backend issue might be the reason.

This change of env variable resolved it for me:
```
export PYTHON_KEYRING_BACKEND=keyring.backends.fail.Keyring
```
Source: [reddit post](https://www.reddit.com/r/learnpython/comments/zcb95y/comment/kdh0aka/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

Just FYI.

**Comment by inducer** [comment]
Thanks for the note. I've had that problem and discovered a similar fix. But is it something that's wrong with Relate? It more seems like a bug in Poetry, unless there's something that we're doing in `pyproject.toml` that's causing this. At any rate, I guess I will add this to the documentation, to avoid people getting bitten.
