### ISSUE TITLE
Check for changed page types

### ISSUE THREAD

**Issue by inducer** [inducer/relate#107]
* Store the question type with FlowPageVisit rows.
* During validation, if existing data is found for one question type, don't validate for different question types.

**Comment by inducer** [comment]
Another option would be to silently ignore data that was produced by a different question type, but that strikes me as a bad idea.

Also, this would likely stop validating for any course where type changes have ever happened and force them to clean up the mess *right now*. Making this a warning rather than an error would allow for a grace period, but the consequences are severe enough that it should probably be prevented very soon. @lukeolson, what do you prefer?

**Comment by lukeolson** [comment]
Ideally an id would have associated with it some immutables, one of them being question type.  The problem with this is that it's set at visit time.  So perhaps

1. associated question type with an id upon first flowpagevisit
2. at validation, check for question type if present

This would allow a change without losing previous history.

**Comment by inducer** [comment]
This includes a migration, so it requires downtime. Not sure I'm itching to schedule downtime for the UIUC instance soon. Maybe if I'm up late sometime on the weekend.
