### ISSUE TITLE
Need enhancement on RecurringEventForm

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#108]
1. Some events happen twice or three times in a week, like 8 am on Monday and 10 am on Wednesday, then user should be allowed to create recurring events for that circumstances.
1. Sometimes we need to postpone or put in advance all the following events, which belong or not belong to the same kind of events, by a specific interval of time. In this case, use ``Edit events`` one by one is horrible.

**Comment by inducer** [comment]
> Some events happen twice or three times in a week, like 8 am on Monday and 10 am on Wednesday, then user should be allowed to create recurring events for that circumstances.

What I do in that case is create two recurring (weekly) event series (or three) and then renumber the result.

> Sometimes we need to postpone or put in advance all the following events, which belong or not belong to the same kind of events, by a specific interval of time. In this case, use Edit events one by one is horrible.

Not sure I understand what you're after... But may be "delete one and renumber" might do the trick? That's what I do when, say, a class gets cancelled.

**Comment by dzhuang** [comment]
Great tricks, thank you !

**Comment by dzhuang** [comment]
These tips are really helpful. Thanks again.
