### ISSUE TITLE
Produce more graceful error message(s) while exploring sample content

### ISSUE THREAD

**Issue by duwhop** [inducer/relate#112]
Hello I'm not sure but I tried to take quiz-text and I get an error when I try to submit the responses to the entire quiz-text:
error at /course/Intro-to-CS/flow-session/2/finish/
[Errno 10061] No connection could be made because the target machine actively refused it

Environment:

Request Method: POST
Request URL: http://localhost:8000/course/Intro-to-CS/flow-session/2/finish/

Django Version: 1.8.4
Python Version: 2.7.6
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'course',
 'crispy_forms',
 'jsonfield',
 'bootstrap3_datetime',
 'djangobower',
 'django_select2',
 'djcelery',
 'kombu.transport.django')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'course.auth.ImpersonateMiddleware',
 'course.exam.ExamFacilityMiddleware',
 'course.exam.ExamLockdownMiddleware')

Traceback:
File "C:\python27_x64\lib\site-packages\django\core\handlers\base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "C:\python27_x64\lib\site-packages\django\utils\decorators.py" in inner
  145.                     return func(*args, **kwargs)
File "C:\Users\kjeanpie\Desktop\SAILS\relate\course\utils.py" in wrapper
  487.         response = f(pctx, *args, **kwargs)
File "C:\Users\kjeanpie\Desktop\SAILS\relate\course\flow.py" in finish_flow_session_view
  1504.                 now_datetime=now_datetime)
File "C:\python27_x64\lib\site-packages\django\utils\decorators.py" in inner
  145.                     return func(*args, **kwargs)
File "C:\Users\kjeanpie\Desktop\SAILS\relate\course\flow.py" in finish_flow_session
  508.                 force_regrade=force_regrade)
File "C:\python27_x64\lib\site-packages\django\utils\decorators.py" in inner
  145.                     return func(*args, **kwargs)
File "C:\Users\kjeanpie\Desktop\SAILS\relate\course\flow.py" in grade_page_visits
  483.                     graded_at_git_commit_sha=fctx.course_commit_sha)
File "C:\Users\kjeanpie\Desktop\SAILS\relate\course\flow.py" in grade_page_visit
  129.             visit.answer, grade_data=grade_data)
File "C:\Users\kjeanpie\Desktop\SAILS\relate\course\page\code.py" in grade
  840.                 page_data, answer_data, grade_data)
File "C:\Users\kjeanpie\Desktop\SAILS\relate\course\page\code.py" in grade
  618.                             recipient_list=[page_context.course.notify_email])
File "C:\python27_x64\lib\site-packages\django\core\mail\__init__.py" in send_mail
  62.     return mail.send()
File "C:\python27_x64\lib\site-packages\django\core\mail\message.py" in send
  303.         return self.get_connection(fail_silently).send_messages([self])
File "C:\python27_x64\lib\site-packages\django\core\mail\backends\smtp.py" in send_messages
  100.             new_conn_created = self.open()
File "C:\python27_x64\lib\site-packages\django\core\mail\backends\smtp.py" in open
  58.             self.connection = connection_class(self.host, self.port, **connection_params)
File "C:\python27_x64\lib\smtplib.py" in __init__
  251.             (code, msg) = self.connect(host, port)
File "C:\python27_x64\lib\smtplib.py" in connect
  311.         self.sock = self._get_socket(host, port, self.timeout)
File "C:\python27_x64\lib\smtplib.py" in _get_socket
  286.         return socket.create_connection((host, port), timeout)
File "C:\python27_x64\lib\socket.py" in create_connection
  571.         raise err

Exception Type: error at /course/Intro-to-CS/flow-session/2/finish/
Exception Value: [Errno 10061] No connection could be made because the target machine actively refused it

I'm not sure how to rectify the issue. Is there something that I'm not doing and should be doing or should have done?

**Comment by inducer** [comment]
Two issues:
* It's trying to use Docker to run the Python code in that quiz. (Docker is Linux-only AFAIK.) Since this fails, it's trying to send email to the course admin. 
* You don't have email set up, so that fails, too--which leaves it to bail out with a traceback.

I can see how this is not ideal behavior for sample content. Maybe this should be handled more gracefully. Let's leave this bug open to track that.

**Comment by duwhop** [comment]
Thank you for looking into this.  I'm not sure if this is a different issue or if this is related, but I also get an error when I submit an answer for the Python segments.

**Comment by inducer** [comment]
Same issue--you won't be able to submit Python code (which RELATE tries to run) without running into this issue.

**Comment by duwhop** [comment]
I see.  So then would I wait until it is supported for windows?

**Comment by inducer** [comment]
Docker is supported on Windows:
https://docs.docker.com/installation/windows/

This appears to work by spawning a LInux VM--but it appears to be supported.

**Comment by duwhop** [comment]
Oh ok.  I downloaded the docker toolbox for windows (https://docs.docker.com/windows/step_one/).  I'm sorry for asking these questions - I'm new.  I tried running the quiz again and I am getting the same error message.  I have my email address (do I need to change it?)

**Comment by inducer** [comment]
You need to set up SMTP in `local_settings.py`.
