### ISSUE TITLE
Feature Request: git SHA dropdown on Update Course page

### ISSUE THREAD

**Issue by bowmanat** [inducer/relate#114]
*Reason for request*
Most of the time I am developing, I am working in a branch.  To get the branch SHA into the box on the Update Course page, I have to go to my repo on the command line and copy the SHA over into RELATE.  Also, when I want someone else to test the branch, I either have to tell them which SHA to use, or they need to have an up-to-date copy of the repo and use git log to find the correct SHA.  None of this is a huge deal, but it requires a little extra time each time I want to test my branch.

*Actual Request*
It would be nice if the "New git SHA*" box were also a dropdown that had the current head of every branch, so all you would need to do is click on the correct branch name.  I am almost always interested in the heads of the branches, so those would be the only commits I would need a shortcut to.

**Comment by inducer** [comment]
I like the idea. Send me a pull request?

* You should be able to get the available branches from `refs` in the `repo` object: https://www.dulwich.io/apidocs/dulwich.repo.Repo.html
* For the HTML UI, I'd suggest this: https://select2.github.io/ -- the [Django wrapper](https://django-select2.readthedocs.org/en/latest/) for that is already included.
* This is the file you'd need to hack: https://github.com/inducer/relate/blob/master/course/versioning.py

**Comment by bowmanat** [comment]
Do you know of anything similar to the Select2 box you suggested, but that also allows for arbitrary text input?

The Select2 box allows selection only from a predetermined set of options. Thus, you have one of two options.  First, you could load only refs into the box, which then does not allow you to go to a non-referenced commit.  Or, second, you could make all of the commits options in the box, but I think this will slow down the loading of the box when there are many commits.

**Comment by inducer** [comment]
Hmm. Maybe the dropdown and the textbox want to be separate, maybe with an "Other" option in the dropdown.

**Comment by bowmanat** [comment]
That could work, especially since the "Other" option would presumably be rarely used (at least in my workflow; I don't know about anyone else).  Unfortunately, I don't have much more time to dedicate to this at the moment.

So far, I implemented the Select2 box as originally suggested by you.  I chose to add all the commits to the box.  It's a pretty good interface, and I haven't noticed any issues of speed in my local testing.  I put it in my fork of your repo, in the 'sha-dropdown' branch, in case you want to have a look.

**Comment by inducer** [comment]
Can you click the "pull request" button on that branch?

**Comment by bowmanat** [comment]
You should revert that commit for now.

It is apparently not getting all the refs, just HEAD and master and none of the branches.  With the way the commit list is compiled, this means any commits that are not ancestors of master do not show up in the list, and thus cannot be previewed.

Sorry for the mistake.  I'm looking into how to get all the refs and will let you know when I figure it out.

**Comment by inducer** [comment]
K, reverted.

**Comment by inducer** [comment]
(Back in.)
