### ISSUE TITLE
Brocken Latex

### ISSUE THREAD

**Issue by yslan** [inducer/relate#1160]
[Example](https://relate.cs.illinois.edu/course/cs450-f24/flow-session/896537/0/)
![image](https://github.com/user-attachments/assets/d3a43c93-41b5-4e4d-a511-1d4423afd1af)

It's caused by one of the following three comments. 

611735b1b204a1a2c2d188918e555e047c56ad11
2489b60d1a9f78ee2781f6cb7ac07e616a8b5a3b
3132d672c2f6037544a3dc6d524d5d36523d0090

**Comment by inducer** [comment]
Again? :cry: 

Thanks for letting me know. I've reverted `relate.cs`, should be OK there. Oddly, I can't reproduce this in my development environment. It's a bit of a mystery.

**Comment by yslan** [comment]
Thanks. It's fixed on my screen.

**Comment by inducer** [comment]
I forgot to bump the markup cache version (e951e0a22b6ce24c24805df280fba478ccc762c9) for the changes in #1159.
