### ISSUE TITLE
A student complaints about multiple form submission when starting a flow

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#123]
As there is a mechanism to prevent that according to [this line](https://github.com/inducer/relate/blob/master/course/templates/course/flow-start.html#L170), and I cannot reproduce the result, but it seems that will happen according to [this question and solution](http://stackoverflow.com/questions/15807471/prevent-multiple-form-submissions-using-angular-js-disable-form-button).

**Comment by inducer** [comment]
The Javascript approach to this is not bullet-proof. If you reload the page fast enough, or if you open it in two separate windows, (or if you have JS turned off...?) you *can* submit two start flow requests one right after the other. *If* you are using Postgresql as your database, then the processing of the requests should be race-free. (say, in checking `if_has_fewer_sessions_than`) But beyond that, there's not much the system can do--if it receives two legitimate requests that say "start this flow", then it needs to act on them.

**Comment by dzhuang** [comment]
Thank you for your explanation. I didn't turn off JS and I am actually using Postgresql as my database backend. The student report that every time he clicks on the start button, there will be 2 new sessions created, because something malfunctions in his computer. Maybe I need to use server side tricks to prevent multiple sessions from being created, within a reasonable time interval, by a single user.

**Comment by inducer** [comment]
I actually like the prevent-two-sessions-in-close-succession idea. Pull request?

**Comment by dzhuang** [comment]
I am glad to have a try when I have time.
2015年10月16日 上午10:26，"Andreas Klöckner" <notifications@github.com>写道：

**Comment by dzhuang** [comment]
Tried to fix it by 7fddd2dea026ae661f8a9bd4b819731a90fc11f9.

**Comment by dzhuang** [comment]
New session won't be created when using faked time, in conditions when the fake time is ahead of the real time the session was created. I'll try to fix it later.

**Comment by dzhuang** [comment]
Fixed by https://github.com/inducer/relate/pull/141.

**Comment by inducer** [comment]
#141 merged
