### ISSUE TITLE
Seems to sometimes pick the wrong localization

### ISSUE THREAD

**Issue by inducer** [inducer/relate#127]
![upload_file_2](https://cloud.githubusercontent.com/assets/352067/11017715/f6189dce-856d-11e5-96f6-fa208be090f6.png)

@mattwala: Can you share what your browser sends for the `Accept-Language` header?

**Comment by mattwala** [comment]
It looks like it sends en-US,en;q=0.8

**Comment by inducer** [comment]
FYI: https://docs.djangoproject.com/en/1.8/topics/i18n/translation/#lazy-translation

**Comment by inducer** [comment]
If non-lazy, you get whose locale was active when the module was first imported. And it looks like at least one of the 10-ish RELATE app worker processes got lucky and had someone with a Chinese locale be the first to access a file upload question.

**Comment by inducer** [comment]
At any rate, thanks for reporting this.
