### ISSUE TITLE
bug report on latest commit (bbc546102b95ea49a3cdfa18f84e17e558d0f990)

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#13]
With recent commit  bbc546102b95ea49a3cdfa18f84e17e558d0f990, there appear some errors which don't exist in the past commits:

 (1). Unable to start a quiz, with the following debug message:

```
ValueError at /course/relate-sample/flow/quiz-test/start/
list.remove(x): x not in list
Request Method:	POST
Request URL:	http://127.0.0.1:8000/course/relate-sample/flow/quiz-test/start/
Django Version:	1.8
Exception Type:	ValueError
Exception Value:	
list.remove(x): x not in list
Exception Location:	\path\to\relate\course\content.py in add_page, line 842
```

 (2). Time zone error, which doesn't exist in commits before under the same environment (Windows 7, django 1.8, mysql 5.6).

```
ValueError at /admin/course/flowpagevisit/
Database returned an invalid value in QuerySet.datetimes(). Are time zone definitions for your database and pytz installed?
Request Method:	GET
Request URL:	http://127.0.0.1:8000/admin/course/flowpagevisit/
Django Version:	1.8
Exception Type:	ValueError
Exception Value:	
Database returned an invalid value in QuerySet.datetimes(). Are time zone definitions for your database and pytz installed?
```

That error disappears when `USE_TZ = False`, however, that will cause the following error like grant exception which require '`USE_TZ = True`. 

```
ValueError at /course/relate-sample/grant-exception/31/quiz-test/
astimezone() cannot be applied to a naive datetime
```

**Comment by inducer** [comment]
Please open one issue per problem that you're having.

The first issue you reported should be fixed as of b94682d.

I've never observed anything like the second issue with Postgresql on Linux. The error message makes it look a bit like an installation problem with you r database, so please verify that. I'll close this bug in the meantime. Please reopen it if you think there's something that Relate is legitimately doing wrong.
