### ISSUE TITLE
Python code submission fails

### ISSUE THREAD

**Issue by duwhop** [inducer/relate#135]
Hello I am having trouble submitting python code from question 8 quiz.  I get the following error:

Autograder feedback
The grading code failed. Sorry about that. The staff has been informed, and if this problem is due to an issue with the grading code, it will be fixed as soon as possible. In the meantime, you'll see a traceback below that may help you figure out what went wrong.

This is the exception traceback:

Traceback (most recent call last):
  File "C:\Users\kjeanpie\Desktop\SAILS\relate\course\page\code.py", line 565, in grade
    run_timeout=self.page_desc.timeout)
  File "C:\Users\kjeanpie\Desktop\SAILS\relate\course\page\code.py", line 250, in request_python_run_with_retries
    result = request_python_run(run_req, run_timeout, image=image)
  File "C:\Users\kjeanpie\Desktop\SAILS\relate\course\page\code.py", line 109, in request_python_run
    user="runpy")
  File "C:\python27_x64\lib\site-packages\docker\client.py", line 245, in create_container
    return self.create_container_from_config(config, name)
  File "C:\python27_x64\lib\site-packages\docker\client.py", line 252, in create_container_from_config
    res = self._post_json(u, data=config, params=params)
  File "C:\python27_x64\lib\site-packages\docker\clientbase.py", line 128, in _post_json
    return self._post(url, data=json.dumps(data2), **kwargs)
  File "C:\python27_x64\lib\site-packages\docker\clientbase.py", line 83, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "C:\python27_x64\lib\site-packages\requests\sessions.py", line 508, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\python27_x64\lib\site-packages\requests\sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\python27_x64\lib\site-packages\requests\sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "C:\python27_x64\lib\site-packages\requests\adapters.py", line 370, in send
    timeout=timeout
  File "C:\python27_x64\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "C:\python27_x64\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\python27_x64\lib\httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "C:\python27_x64\lib\httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "C:\python27_x64\lib\httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "C:\python27_x64\lib\httplib.py", line 829, in _send_output
    self.send(msg)
  File "C:\python27_x64\lib\httplib.py", line 791, in send
    self.connect()
  File "C:\python27_x64\lib\site-packages\docker\unixconn\unixconn.py", line 39, in connect
    sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
AttributeError: 'module' object has no attribute 'AF_UNIX'

I am using a Windows machine (10).

**Comment by inducer** [comment]
8f6897c exposes the docker command interface as a setting (previously it defaulted to a Unix socket, hence your error). In your `local_settings.py`, simply change this to `"http://localhost:port/"` (wherever your Docker instance lives):

```
RELATE_DOCKER_URL = "unix://var/run/docker.sock" 
```

**Comment by inducer** [comment]
(reopen if you're still having trouble)

**Comment by duwhop** [comment]
Hello I made the suggested changes, however I still get an error:

Autograder feedback
The grading code failed. Sorry about that. The staff has been informed, and if this problem is due to an issue with the grading code, it will be fixed as soon as possible. In the meantime, you'll see a traceback below that may help you figure out what went wrong.

This is the exception traceback:

Traceback (most recent call last):
  File "C:\Users\kjeanpie\Desktop\SAILS\relate\course\page\code.py", line 566, in grade
    run_timeout=self.page_desc.timeout)
  File "C:\Users\kjeanpie\Desktop\SAILS\relate\course\page\code.py", line 251, in request_python_run_with_retries
    result = request_python_run(run_req, run_timeout, image=image)
  File "C:\Users\kjeanpie\Desktop\SAILS\relate\course\page\code.py", line 99, in request_python_run
    version='1.12', timeout=docker_timeout)
  File "C:\python27_x64\lib\site-packages\docker\clientbase.py", line 34, in __init__
    base_url = utils.parse_host(base_url)
  File "C:\python27_x64\lib\site-packages\docker\utils\utils.py", line 277, in parse_host
    "Invalid port: %s", addr
DockerException: ('Invalid port: %s', 'localhost:8000/')

**Comment by inducer** [comment]
You're going to have to include the `http://`.

**Comment by inducer** [comment]
Perhaps also get rid of the trailing slash.

**Comment by duwhop** [comment]
Hello,

I've done both of those.  When I exclude the trailing slash I get a different error: 

Autograder feedback
The grading code failed. Sorry about that. The staff has been informed, and if this problem is due to an issue with the grading code, it will be fixed as soon as possible. In the meantime, you'll see a traceback below that may help you figure out what went wrong.

This is the exception traceback:

Traceback (most recent call last):
  File "C:\Users\kjeanpie\Desktop\SAILS\relate\course\page\code.py", line 566, in grade
    run_timeout=self.page_desc.timeout)
  File "C:\Users\kjeanpie\Desktop\SAILS\relate\course\page\code.py", line 251, in request_python_run_with_retries
    result = request_python_run(run_req, run_timeout, image=image)
  File "C:\Users\kjeanpie\Desktop\SAILS\relate\course\page\code.py", line 110, in request_python_run
    user="runpy")
  File "C:\python27_x64\lib\site-packages\docker\client.py", line 245, in create_container
    return self.create_container_from_config(config, name)
  File "C:\python27_x64\lib\site-packages\docker\client.py", line 253, in create_container_from_config
    return self._result(res, True)
  File "C:\python27_x64\lib\site-packages\docker\clientbase.py", line 108, in _result
    self._raise_for_status(response)
  File "C:\python27_x64\lib\site-packages\docker\clientbase.py", line 103, in _raise_for_status
    raise errors.NotFound(e, response, explanation=explanation)
NotFound: 404 Client Error: NOT FOUND ("<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <title>Page not found at /v1.12/containers/create</title>
  <meta name="robots" content="NONE,NOARCHIVE">
  <style type="text/css">
    html * { padding:0; margin:0; }
    body * { padding:10px 20px; }
    body * * { padding:0; }
    body { font:small sans-serif; background:#eee; }
    body>div { border-bottom:1px solid #ddd; }
    h1 { font-weight:normal; margin-bottom:.4em; }
    h1 span { font-size:60%; color:#666; font-weight:normal; }
    table { border:none; border-collapse: collapse; width:100%; }
    td, th { vertical-align:top; padding:2px 3px; }
    th { width:12em; text-align:right; color:#666; padding-right:.5em; }
    #info { background:#f6f6f6; }
    #info ol { margin: 0.5em 4em; }
    #info ol li { font-family: monospace; }
    #summary { background: #ffc; }
    #explanation { background:#eee; border-bottom: 0px none; }
  </style>
</head>
<body>
  <div id="summary">
    <h1>Page not found <span>(404)</span></h1>
    <table class="meta">
      <tr>
        <th>Request Method:</th>
        <td>POST</td>
      </tr>
      <tr>
        <th>Request URL:</th>
        <td>http://localhost:8000/v1.12/containers/create</td>
      </tr>
      
    </table>
  </div>
  <div id="info">
    
      <p>
      Using the URLconf defined in <code>relate.urls</code>,
      Django tried these URL patterns, in this order:
      </p>
      <ol>
        
          <li>
            
                ^login/$
                [name='relate-sign_in_by_user_pw']
            
          </li>
        
          <li>
            
                ^login/sign-up/$
                [name='relate-sign_up']
            
          </li>
        
          <li>
            
                ^login/reset-password/$
                [name='relate-reset_password']
            
          </li>
        
          <li>
            
                ^login/reset-password/stage-2/(?P&lt;user_id&gt;[0-9]+)/(?P&lt;sign_in_key&gt;[a-zA-Z0-9]+)
                [name='relate-reset_password_stage2']
            
          </li>
        
          <li>
            
                ^login/by-email/$
                [name='relate-sign_in_by_email']
            
          </li>
        
          <li>
            
                ^login/token/(?P&lt;user_id&gt;[0-9]+)/(?P&lt;sign_in_key&gt;[a-zA-Z0-9]+)/$
                [name='relate-sign_in_stage2_with_token']
            
          </li>
        
          <li>
            
                ^logout/$
                [name='relate-logout']
            
          </li>
        
          <li>
            
                ^profile/$
                [name='relate-user_profile']
            
          </li>
        
          <li>
            
                ^generate-ssh-key/$
                [name='relate-generate_ssh_keypair']
            
          </li>
        
          <li>
            
                ^monitor-task/(?P&lt;task_id&gt;[-0-9a-f]+)$
                [name='relate-monitor_task']
            
          </li>
        
          <li>
            
                ^user/impersonate/$
                [name='relate-impersonate']
            
          </li>
        
          <li>
            
                ^user/stop_impersonating/$
                [name='relate-stop_impersonating']
            
          </li>
        
          <li>
            
                ^time/set-fake-time/$
                [name='relate-set_fake_time']
            
          </li>
        
          <li>
            
                ^time/set-pretend-facilities/$
                [name='relate-set_pretend_facilities']
            
          </li>
        
          <li>
            
                ^$
                [name='relate-home']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/$
                [name='relate-course_page']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/instant-message/$
                [name='relate-send_instant_message']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/sandbox/markup/$
                [name='relate-view_markup_sandbox']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/sandbox/page/$
                [name='relate-view_page_sandbox']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/grading/my/$
                [name='relate-view_participant_grades']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/grading/participant/(?P&lt;participation_id&gt;[0-9]+)/$
                [name='relate-view_participant_grades']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/grading/participants/$
                [name='relate-view_participant_list']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/grading/opportunities/$
                [name='relate-view_grading_opportunity_list']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/grading/overview/$
                [name='relate-view_gradebook']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/grading/overview/csv/$
                [name='relate-export_gradebook_csv']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/grading/by-opportunity/(?P&lt;opp_id&gt;[0-9]+)/$
                [name='relate-view_grades_by_opportunity']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/grading/single-grade/(?P&lt;participation_id&gt;[0-9]+)/(?P&lt;opportunity_id&gt;[0-9]+)/$
                [name='relate-view_single_grade']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/grading/reopen-session/(?P&lt;flow_session_id&gt;[0-9]+)/(?P&lt;opportunity_id&gt;[0-9]+)/$
                [name='relate-view_reopen_session']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/grading/csv-import/$
                [name='relate-import_grades']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/grading/flow-page/(?P&lt;flow_session_id&gt;[0-9]+)/(?P&lt;page_ordinal&gt;[0-9]+)/$
                [name='relate-grade_flow_page']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/grading/statistics/(?P&lt;flow_id&gt;[-_a-zA-Z0-9]+)/$
                [name='relate-show_grading_statistics']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/enroll/$
                [name='relate-enroll']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/preapprove/$
                [name='relate-create_preapprovals']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/media/(?P&lt;commit_sha&gt;[a-f0-9]+)/(?P&lt;media_path&gt;.*)$
                [name='relate-get_media']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/file-version/(?P&lt;commit_sha&gt;[a-f0-9]+)/(?P&lt;path&gt;.*)$
                [name='relate-get_repo_file']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/f/(?P&lt;path&gt;.*)$
                [name='relate-get_current_repo_file']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/create-recurring-events/$
                [name='relate-create_recurring_events']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/renumber-events/$
                [name='relate-renumber_events']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/calendar/$
                [name='relate-view_calendar']
            
          </li>
        
          <li>
            
                ^new-course/$
                [name='relate-set_up_new_course']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/update/$
                [name='relate-update_course']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/flow/(?P&lt;flow_id&gt;[-_a-zA-Z0-9]+)/start/$
                [name='relate-view_start_flow']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/flow-session/(?P&lt;flow_session_id&gt;[0-9]+)/(?P&lt;ordinal&gt;[0-9]+)/$
                [name='relate-view_flow_page']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/flow-session/(?P&lt;flow_session_id&gt;[-0-9]+)/update-expiration-mode/$
                [name='relate-update_expiration_mode']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/flow-session/(?P&lt;flow_session_id&gt;[0-9]+)/finish/$
                [name='relate-finish_flow_session_view']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/test-flow/$
                [name='relate-test_flow']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/instant-flow/$
                [name='relate-manage_instant_flow_requests']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/regrade-flows/$
                [name='relate-regrade_flows_view']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/grant-exception/$
                [name='relate-grant_exception']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/grant-exception/(?P&lt;participation_id&gt;[0-9]+)/(?P&lt;flow_id&gt;[-_a-zA-Z0-9]+)/$
                [name='relate-grant_exception_stage_2']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/grant-exception/(?P&lt;participation_id&gt;[0-9]+)/(?P&lt;flow_id&gt;[-_a-zA-Z0-9]+)/(?P&lt;session_id&gt;[0-9]+)/$
                [name='relate-grant_exception_stage_3']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/flow-analytics/$
                [name='relate-flow_list']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/flow-analytics/(?P&lt;flow_id&gt;[-_a-zA-Z0-9]+)/$
                [name='relate-flow_analytics']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/flow-analytics/(?P&lt;flow_id&gt;[-_a-zA-Z0-9]+)/page/(?P&lt;group_id&gt;[-_a-zA-Z0-9]+)/(?P&lt;page_id&gt;[-_a-zA-Z0-9]+)/$
                [name='relate-page_analytics']
            
          </li>
        
          <li>
            
                ^issue-exam-ticket/$
                [name='relate-issue_exam_ticket']
            
          </li>
        
          <li>
            
                ^course/(?P&lt;course_identifier&gt;[-a-zA-Z0-9]+)/batch-issue-exam-tickets/$
                [name='relate-batch_issue_exam_tickets']
            
          </li>
        
          <li>
            
                ^exam-check-in/$
                [name='relate-check_in_for_exam']
            
          </li>
        
          <li>
            
                ^select2/
                
            
          </li>
        
          <li>
            
                ^admin/
                
            
          </li>
        
      </ol>
      <p>The current URL, <code>v1.12/containers/create</code>, didn't match any of these.</p>
    
  </div>

  <div id="explanation">
    <p>
      You're seeing this error because you have <code>DEBUG = True</code> in
      your Django settings file. Change that to <code>False</code>, and Django
      will display a standard 404 page.
    </p>
  </div>
</body>
</html>")

**Comment by inducer** [comment]
First, a tip: Enclose literal blocks in triple quotes to avoid Markdown formatting.

I think you might be getting close. Try saying `docker pull inducer/relate-runpy-i386` on the command line and retry what you just did.

**Comment by duwhop** [comment]
Ok will do.  Sorry about that.  
I ran the suggested commands and get the following message.  
Using default tag: latest
Post http://127.0.0.1:2375/v1.20/images/create?fromImage=inducer%2Frelate-runpy-i386%3Alatest: dial tcp 127.0.0.1:2375: ConnectEx tcp: No connection could be made because the target machine actively refused it..
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?

I am unable to find how to start the docker daemon or even check if it is running on a windows comp.  Any suggestions?

**Comment by inducer** [comment]
https://docs.docker.com/engine/installation/windows/#running-a-docker-container

**Comment by duwhop** [comment]
Hello,  Not too sure.  I followed the instructions on the link and started the container.  I still see the same errors with and without the trailing slash.

**Comment by inducer** [comment]
It looks like the idea is that Docker runs inside of a virtual machine, so you'd have to (a) get Docker listening on an HTTP port and then (b) expose that port to the host computer (but ideally not the rest of the internet).
