### ISSUE TITLE
install requirements.txt issue

### ISSUE THREAD

**Issue by duwhop** [inducer/relate#137]
Hello,

I was running relate on a windows system and then decided since I was having issues then I would switch to unix, however I can't get past the pip install -r requirements.txt command.  What should I do?  I get the following errors before the prompt returns.
dulwich/_objects.c:20:20: fatal error: Python.h: No such file or directory

compilation terminated.

error: command 'i686-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-ykxHJZ-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-lcrWnA-record/install-record.txt --single-version-externally-managed --compile --user failed with error code 1 in /tmp/pip-ykxHJZ-build
Storing debug log for failure in /home/kjeanpie/.pip/pip.log

**Comment by duwhop** [comment]
using ubuntu 15.10

**Comment by inducer** [comment]
Install the python-dev package.
