### ISSUE TITLE
fix typo in local settings example

### ISSUE THREAD

**Issue by gvelez17** [inducer/relate#14]
diff --git a/local_settings.py.example b/local_settings.py.example
index ef3a482..49138e2 100644
--- a/local_settings.py.example
+++ b/local_settings.py.example
@@ -63,7 +63,7 @@ TIME_ZONE = "America/Chicago"
 
 # Uncomment one of these to choose the default sign-in method for students
 STUDENT_SIGN_IN_VIEW = "relate-sign_in_by_email"
-#STUDENT_SIGN_IN_VIEW = "relate-sign_in_by_user_bw"
+#STUDENT_SIGN_IN_VIEW = "relate-sign_in_by_user_pw"
 #STUDENT_SIGN_IN_VIEW = "relate-sign_in_by_sso"  # not yet implemented

**Comment by gvelez17** [comment]
(sorry I couldn't get the pull request in, it didn't let me create a branch, let me know if there is another way to submit a pull request)

**Comment by inducer** [comment]
Good catch. Thanks for the report.
