### ISSUE TITLE
missing dependencies?

### ISSUE THREAD

**Issue by gvelez17** [inducer/relate#15]
hi, so after following the installation guide instructions, I'm missing a bunch of the static deps, there is probably some simple command to install these, but its not in the installation guide I don't think.  Probably something to do with conf.py?  If I figure it out I will post it here...

![image](https://cloud.githubusercontent.com/assets/798887/7437936/8553135e-f011-11e4-8392-e3f51e4632e7.png)

**Comment by inducer** [comment]
* Did you run `python manage.py bower install`? Did it succeed? (Requires `bower`.)
* If you're not using `python manage.py runserver`, you'll also need to run `python manage.py collectstatic` after that, and then point your webserver at the right directory for the static content.

**Comment by gvelez17** [comment]
yeah, I believe I did both `python manage.py bower install` and `python manage.py collectstatic`.  In any case I just finished installing all the missing things manually so its working nicely now
if I install from scratch again I'll document those steps and if they are still missing after

**Comment by dzhuang** [comment]
Sorry for late response. 

I've encounter the same problem before. When you are under debug mode, i.e., with ``debug = True`` in ``local_setting.py``, there's no need for ``collectstatic``.  If you'd like to use static files in ``/components`` and ``/relate/static`` directories with  ``debug = False`` , you can start the server by: 

```
python manage.py runserver 0.0.0.0:80 --insecure &
```

However, for security reason, you'd better use deploy mode. That where ``collectstatic`` makes sense. Pls. refer to <https://docs.djangoproject.com/en/dev/howto/deployment/>.

**Comment by gvelez17** [comment]
Thanks!  No problem, we're doing a lot of different things

**Comment by inducer** [comment]
Is this still an issue?

**Comment by gvelez17** [comment]
No, we're doing something sort of entirely different now, that project is
on hold.  So not an issue for us, thanks

--G

On Sat, Aug 22, 2015 at 11:44 AM, Andreas Klöckner <notifications@github.com
