### ISSUE TITLE
About the format of full_name of users

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#152]
As of [this method](https://github.com/inducer/relate/blob/f2c09a0806432014764f355d082ab6491646f876/accounts/models.py#L138), we can generate user full name. I see first_name, last_name are used in a select input such as impersonating, selecting sessions when grant exceptions, and in email. However the tradition of name format differs for different countries. In most countries, user fullname takes the format ``first_name + a space + lastname`` as what is defined in the User model. However, in countries like China, Japan and Korea, the format is ``last_name + first_name`` (without space). It looks weird for a Chinese name to be displayed in the format of the western style.

There can be an idea that we can determine from the [characters in the name string](http://stackoverflow.com/questions/1366068/whats-the-complete-range-for-chinese-characters-in-unicode) to decide which format should be used. Is that reasonable? If yes, should we save it into the database as a field when the save() method of User is called, so that less computation is required.

Another question is I find there are two different styles in citing a user's full name. One is [``first_name + a space + lastname``](https://github.com/inducer/relate/blob/f2c09a0806432014764f355d082ab6491646f876/accounts/models.py#L138) and the other is [``lastname + ", " + first_name``](https://github.com/inducer/relate/blob/master/course/templates/course/grade-flow-page.html#L65). Why we are using different styles?

**Comment by inducer** [comment]
https://github.com/bitmazk/django-localized-names ?

**Comment by dzhuang** [comment]
That package seems to ask user to input more fields, like ``romanized_first_name`` and ``romanized_last_name``.

**Comment by inducer** [comment]
Yeah, agree. Doesn't look that suitable on closer inspection.

**Comment by dzhuang** [comment]
As discuss here and  [there](https://github.com/inducer/relate/pull/153), I think it's a too huge work to consider all the possibility in terms of l10n. Maybe we can provide some basic format/method like datetime, get_full_name, and provide some APIs allow users to define their own custom ones if they really need customized ones. 

Beyond that, in the template (base/course_page/flow_page) allow user to include their own customized css and js.

**Comment by inducer** [comment]
Followed up in #153.
