### ISSUE TITLE
datatables-fixedcolumns css name changed.

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#154]
"datatables-fixedcolumns/css/dataTables.fixedColumns.css" [here] (https://github.com/inducer/relate/blob/e85bbc49f3aef4d4c96ec692e0e2f9af02734770/course/templates/course/gradebook-participant-list.html#L16) and all over the project seems need to be changed to "datatables-fixedcolumns/css/fixedColumns.dataTables.scss" [src](https://github.com/DataTables/FixedColumns/tree/master/css). It's weird that the version number is the same (3.1.0).

**Comment by inducer** [comment]
SCSS is actually an input syntax for SASS:

http://www.sitepoint.com/6-current-options-css-preprocessors/

(and not real CSS)

We'll have to find a bower repository that includes the built (actual `.css`) versions.
