### ISSUE TITLE
How to create roll_call flow sessions? 

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#165]
I know roll call records can be imported into relate as a grade opportunity from a csv. But now I want to do it by using the grade_flow_page, roll calling in class using my phone or computer. That means I need to immediately create-start-end a (expecting feedback) flow session for each student. Then in the grade_flow_page I can directly grade the attendance.  Any suggestion how I can manage to do that?

**Comment by inducer** [comment]
What do you have in mind? Are the students going to click a button on the web to indicate "I'm here", or are you going to call their names and check them off the list?

**Comment by dzhuang** [comment]
For now ,my idea is, there can be an invisible session for every student at each lecture. I will do roll call randomly. When there's no roll call they can earn full point by default. The session will display in calendar, and they can ask for leave before the lecture by submitting that session with some material to ask for permission. During roll call I think I can just use grade_flow_page. If a student is absent and if he/she didn't ask for leave, I will give 0 points for his session, else just skip that session with full score, and jump to next student's session.

There's a few problems: 
  1. Is it possible to create such session using current framework, if not, where should I tweak?
  1. I want to enable that session for every lecture, reducing the requirements to write a flow for each lecture.
  1. how to deal with student who did not sign up but preapproved, or whose inst_id/name is not verified?

**Comment by inducer** [comment]
Honestly, if you're doing the roll call manually, I would just use an Excel sheet and use the "import grades from csv" function.

I'd only use flows if the students are actually interacting with something.

> how to deal with student who did not sign up but preapproved, or whose inst_id/name is not verified?

if you do your roll call off an official roster, problem solved. Alternatively, you were speaking of a CSV import somewhere (don't recall where)--that'd work, too.
