### ISSUE TITLE
Deciding enrollment by clicking a link in email?

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#168]
We can generate a approving_key just like what you've done on sign_in_key. In this way we'll have another option beside nevigating to admin and checking those boxes.

**Comment by inducer** [comment]
I like the idea in principle, but it's complicated in practice. In particular, I'd only want to make that kind of change to the database in response to a `POST` request. Now you can only send `GET` requests by clicking links. So, at the very least, you'd need some JS hackery.

**Comment by dzhuang** [comment]
I think 88aeeb8e4afc0a582031c36d8c9924a8849a3e85 provided a better solution.
