### ISSUE TITLE
csv grade import failed when non-Ascii characters were to be imported

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#181]
In cases when a to-be-imported csv, which is not utf-8 encoded, contains non-Ascii characters in the feedback column, and that feedback column is to be imported, it raised UnicodeDecodeError. However, it works well when that column is not imported regardless of the encoding of the csv.

**Comment by inducer** [comment]
FYI: I'm not likely to have time to look into this right now, but I'd be happy to merge a patch.

**Comment by dzhuang** [comment]
Ok, I'll make a PR.
2016年3月1日 上午1:19，"Andreas Klöckner" <notifications@github.com>写道：

**Comment by dzhuang** [comment]
Fixed in 622d9666c95f8138c00cfa25c1db6e957fa16bc0.
