### ISSUE TITLE
save operation doesn't make sense for upload question

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#193]
For an upload question, if the page is saved, then submitting still require to re-upload file since the form is emptied, and the answer-data is not loaded to the form (which seems not possible). 

Maybe we can add an attribute to determine if there should be a save button in each kind of page, and add button according to that setting.

**Comment by inducer** [comment]
Not sure what you mean. In my usage, "Save answer" works, although it's not particularly distinct from the "Submit for Feedback" button right next to it. (I use `FileUploadPage` with `can_change_answer`.)

**Comment by dzhuang** [comment]
I also use it with ``can_change_answer``. My students thought the two button are different. Someone saved the answer first, and when they decide to submit the answer, they clicked the "Submit for Feedback" button, but the form ask them to upload the file again.

I think the "Save answer" button makes sence for TextQuestions and ChoiceQuestion, because those page can load the form with saved answer-data when the request is GET. But for upload question, the save button is redundant, especially when users may change answer.

**Comment by inducer** [comment]
OIC. Yeah, I agree. it's redundant. I'd be happy to take a not-too-gross patch that gets rid of it.

**Comment by dzhuang** [comment]
Fixed by #194 .
