### ISSUE TITLE
FlowPageVisit bug?

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#199]
After the instructor/TAs visited an attendant's flow pages, ``FlowPageVisit`` instances will be saved as if it is that attendant who had made those visits. I don't know if it is actually a bug or it is intended to be designed in this way. 

If it's a bug, then I think it's better that when impersonating, there should be no new instance saved or save the user who is impersonating as the ``participant``.

*Update*:
I am wrong in that actually ``FlowPageVisit`` doesn't have a property recording the visitor, the ``participant`` property displayed in Admin is from the related ``flow_session.participation.user``. I think it's better not to save those instances when the visit is make by course staff.

For impersonating, however, if the course staff submit answer for the attendants, is it possible to distinguish those visits from the actual visits made by the participants themselves?

**Comment by inducer** [comment]
I think we simply should add `user` and `impersonated_by` columns to the flow page visit. That way, we keep a record of the whole truth and can defer the decision of what to do with the facts to pieces of code actually using the information.
