### ISSUE TITLE
Feature Request:  Analytics Ignore TA/Instructor Sessions

### ISSUE THREAD

**Issue by eecarrier** [inducer/relate#208]
Currently analytics for a grading opportunity (accessed via "View Analytics" button on the grading opportunity page) appear to include instructor and TA sessions.  This skews distributions.  It would be nice if these were excluded from the analytics.

**Comment by inducer** [comment]
That sounds like a good idea, and it should only be a few lines of code. I don't currently have time to look into this, but I'd be happy to take a patch.
