### ISSUE TITLE
Extending APIs for pages

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#213]
1. Sometimes it is needed to include ``page_context`` into ``page.make_page_data`` method. For example, I want to load a repo data file with a number of different questions, and ask student to do one of them randomly. In that case, I want to store the question he/she was provided in page_data. However, to load the repo file, I need to use the ``page_context`` data.

1. Include ``request`` parameter in ``page.correct_answer`` method, so that I can provide an abstract answer for students while provide a detailed answer for TAs.

Are those ideas plausible? (I know how to do it.)

**Comment by inducer** [comment]
1.  Sure, no objections.
2.  My gut feeling says those are two separate things, which should use different terminology (i.e. different methods) rather than opaquely dispatching on a `request` property inside the method. I could see adding a "role" argument, and, if the `correct_answer`bit in the YAML is a dictionary, then do a lookup by role.

How does that sound?

**Comment by dzhuang** [comment]
For the 2nd point,  I admit I made a mistake, using ``page_context.flow_session.participation.role`` as you suggested can make it happen if I want to have different correct_answer for different roles. But for more complex case, for example, only display detailed answer in grading page, then the ``request`` argument is necessary?

**Comment by inducer** [comment]
I would not suggest getting the role that way. Instead, let's make it part of the official interface so that it is clear and obvious that different solutions may be returned based on the role.

**Comment by dzhuang** [comment]
Another idea, I am defining my own page type according to [this](https://documen.tician.de/relate/flow.html#definining-your-own-page-types). Besides above mentioned requests on extra parameter ``page_context`` in ``make_page_data``, I need another functionality.

I use ``page_data`` to store the randomly selected data from a repo file to generate questions for different student, which need ``page_context`` in ``make_page_data``.

Then I need to use some python method ( which is in ``page_desc``) to generate the html code of those questions, and because that method is expensive, I wish to avoid running that method frequently, thus I need to use cache. So I need to use some strings to construct a unique cache key, which including both the information of the question, and the python code of the method. For the latter, because if I changed the code of the method, the html code might have different result. 

It seem I need to expand the page API again. My current idea is to store some md5 string in page_data. That require a method which might be named ``update_page_data``, and it can be called in ``add_page`` in ``course.flow._adjust_flow_session_page_data_inner``. In this way, page_data will be adjusted when course repo is updated.

What's your suggestion?
