### ISSUE TITLE
Warning: django-bower not support Django version 1.9.5 above

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#223]

**Comment by inducer** [comment]
Where'd you see this?

**Comment by dzhuang** [comment]
https://github.com/nvbn/django-bower/issues/68

**Comment by inducer** [comment]
Uh-oh. That's no good. Can you get things going enough by temporarily going to 1.9.5?

**Comment by dzhuang** [comment]
I have recently upgraded to 1.10 and I remember it worked for 1.9.5. But it seems 1.9.5 will have compatibility issue for commits which drop support for ``RequestContext``.
