### ISSUE TITLE
New issues when creating a new course

### ISSUE THREAD

**Issue by swdever** [inducer/relate#229]
Hello,
I encounter an error when creating a new course. The RELATE is running on a Ubuntu machine. It sends me the error message below through the browser after push the "Validate and create" button.

**Course creation failed: UnboundLocalError: local variable 'repo' referenced before assignment**

I use  git://github.com/inducer/relate-sample as the git source since I am a beginner of RELATE. I have seen the old issue about creating new course, but they are helpless. Please help.

**Comment by inducer** [comment]
Thanks for the report, and sorry for the trouble. Embarrassingly, there *was* an automated test that was supposed to check exactly this, but in addition to the actual bug, your report revealed that the test wasn't working either. That's now fixed, too.
