### ISSUE TITLE
Dividen by zero exception

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#241]
Happens when value of an correct answer is zero, at https://github.com/inducer/relate/blob/master/course/page/text.py#L511

I have no good idea of how to fix this.

**Comment by inducer** [comment]
Same as choice answer: Disallow `rtol` for answer zero.

**Comment by dzhuang** [comment]
My fault. In fact it is [there](https://github.com/inducer/relate/blob/master/course/page/text.py#L462-L467)
