### ISSUE TITLE
Email extension issues

### ISSUE THREAD

**Issue by inducer** [inducer/relate#247]
@dzhuang, I just noticed a few things about #238 that I'd like changed:

* Defaulting `RELATE_EMAIL_SMTP_ALLOW_NONAUTHORIZED_SENDER` to False represents a behavior change.
* That setting should be in `local_settings.example.py`.
* The default for that is in multiple locations, allowing for inconsistency. Don't do that. Instead, do the default in `relate/settings.py`. (And don't use `getattr` with a default after that.)

**Comment by dzhuang** [comment]
sorry for the bugs. I will try to update the code after a week as I am not
in office these days. I hope it's not too late.

2016年10月6日 上午8:39，"Andreas Klöckner" <notifications@github.com>写道：

**Comment by inducer** [comment]
dzhuang <notifications@github.com> writes:
> sorry for the bugs. I will try to update the code after a week as I am not
> in office these days. I hope it's not too late.

No problem at all. I'd just like that to get done eventually.

**Comment by dzhuang** [comment]
Is #248 ok to fix this issue?

**Comment by inducer** [comment]
Yep, that looks OK.
