### ISSUE TITLE
What can bookmark do?

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#250]
I don't understand what bookmarks for flow page are supposed to do. There seems not shortcut that I can see all pages are bookmarked.

**Comment by inducer** [comment]
It's just a way to label pages that you may want to revisit later. On my exams, there are 20-30 questions, and if a student (say) isn't sure about their answer, they can bookmark it and come back to it.

**Comment by dzhuang** [comment]
OIC, thanks for the explanation!
