### ISSUE TITLE
Bug: wrong overall grade when grading criterion changed between multiple submissions

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#263]
Happens when there are several session submissions for a flow by the a same participation, using ``grade_aggregation_strategy.use_latest``, and the grading criterion changed between submission, by that participation. 

 For example, there are four sessions with grading percentages and finished time:
- 10% at 9:00am
- 20% at 9:01am
- 30% at 9:02am
- 100% at 10:00am, after grading criterion changed (at 9:30 am)

According to current mechanism, the last session will get correct grade, and the former 3 will be regraded using regrade or recalculate task. Because the last session won't generate a new instance of ``GradeChange``, the former 3 session will, and as of [this line](https://github.com/inducer/relate/blob/master/course/models.py#L1595),  the overall grading will be using the percentage of the 3rd session's, which is 30%, according to [this line](https://github.com/inducer/relate/blob/master/course/models.py#L1625).

**Comment by inducer** [comment]
*   What is a "grading criterion"? The aggregation strategy?

*   > Because the last session won't generate a new instance of GradeChange

    Why?

**Comment by dzhuang** [comment]
1. Sorry for my bad English. I used "change grading criterion" to refer to, for example, the answer previous supposed to be wrong is changed to be correct.
1. Because the last session has already got a correct grading, its points/comment/max_points are not changed when all the sessions of an opp is regraded or recalculated, while [these lines](https://github.com/inducer/relate/blob/master/course/flow.py#L1082-L1085) says the GradeChange instance don't need to be saved ``do_save=False``.

**Comment by inducer** [comment]
(IMO) same as #417, closing as a duplicate. (#417 has the advantage that I wasn't being an idiot and actually understood what was happening. I think.)
