### ISSUE TITLE
Question: deploy docker on another server?

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#268]
I'm wondering if it's possible to deploy the runpy docker image on another machine, which can be visited by the Relate instance via public ip? Because my server running the instance is slow with low memory, is it possible to do that under current mechanism?

**Comment by inducer** [comment]
Yes, we do that. In fact, we've got a Docker Swarm installation that distributes the load over a few execution hosts. That works very well, too. I'd recommend it.

**Comment by inducer** [comment]
One wrinkle I should mention is that you'll have to set up TLS keys to make sure your setup is secure. I didn't find that to be overly difficult, but it took a little while.

**Comment by dzhuang** [comment]
That's amazing, and thanks for the feedback and great suggestions.

**Comment by dzhuang** [comment]
Two more stupid question: 

1. Does that require all the random ports which might be used by the containers can be visited on the hosts? As one of the server (FOO) I want use to host the runpy is behind a physical firewall, if the answer is yes, then ask the network administrator to open all the required ports (besides 2375/2376) seems to be a mission impossible.

1. Another problem on docker swarm, due to the physical firewall, that server FOO has an inner ip address which is not accessible directly by my relate instance outside the firewall, and another public ip which can be visited. I test the swarm mode, FOO joined the swarm successfully, but it seem that swarm  take its inner ip instead of the public one, as it display in the swarm status of the manager node that there are susceptive pings from the inner ip and connection fails.

**Comment by inducer** [comment]
> Does that require all the random ports which might be used by the containers can be visited on the hosts?

Yes.

> Another problem on docker swarm, due to the physical firewall, that server FOO has an inner ip address which is not accessible directly by my relate instance outside the firewall, and another public ip which can be visited.

Yeah, I can see how that would be an issue.

FWIW, I have swarm and relate on the same machine, and the runpy instances on different hosts on the same subnet. (They're all virtual machines.)

**Comment by dzhuang** [comment]
Thanks for the reply.
