### ISSUE TITLE
How to determine correctness when page point value is 0 in PythonCodeQuestionWithHumanTextFeedback

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#269]
[This line](https://github.com/inducer/relate/blob/master/course/page/code.py#L1017) will raise ``ZeroDivisionError`` when ``code_feedback is not None``.

That happened when I want user to exercise on an "Optional" page (that's the reason I set the page point value to be 0). Although we can set the grade of the page to 0, there's still a problem how to determine the correctness, it seems we have to arbitrarily set the ratio of ``code_feedback.correctness * code_points``  and ``grade_data["grade_percent"] / 100 * self.page_desc.human_feedback_value``, by half?

**Comment by inducer** [comment]
Right. That's a problem. That should be `human_feedback_percentage`, and maybe we should deprecate `human_feedback_value`.

Could you submit a patch?

**Comment by dzhuang** [comment]
Sure! But I need a few days to handle this as I'm quite busy these days.

**Comment by dzhuang** [comment]
A question, besides the deprecate warning, if we add ``human_feedback_value`` to ``required_attrs``,  then it will fail update validation of repos which work well but didn't use that attribute? How to avoid that?

**Comment by inducer** [comment]
`human_feedback_value` should get moved to `allowed_attrs`. That's also where `human_feedback_percentage` goes. Then, in `__init__`, you check that exactly one of those is present and throw a `ValidationError` if not (i.e. both or neither). Next, if `human_feedback_value` is present, you produce a deprecation warning.
