### ISSUE TITLE
Course specific facilities

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#283]
Currently, facilities are configured at site level, which means restart the instance is required everytime new facilities are added or removed. I think it's better to expand the Course model to allow instructors to configure facilities in course settings.

**Comment by inducer** [comment]
I agree that that would be nicer, and I considered it. There is however a performance concern there: Facilities are queried for every request, and so putting them into the database would incur the cost of one additional database roundtrip for every request.

**Comment by dzhuang** [comment]
OIC, now I understand why it was intentinally dropped the models. Thanks for the explanation!

**Comment by dzhuang** [comment]
Will cache keys which won't expire reduce the burnden?

**Comment by inducer** [comment]
They would, by some amount. But (a) how do you expire those if something does change? and (b) it's a cost that gets paid on *every* request...

**Comment by dzhuang** [comment]
For (a), we can use signals to update the cache keys when faclities instances are saved. For (b), it's really a problem. It seems we have to give up. Thanks.
