### ISSUE TITLE
Indenting multiple lines together using a tab

### ISSUE THREAD

**Issue by unnat** [inducer/relate#289]
I have issues indenting multiple lines of a code (eg. content of a for loop).
I usually select multiple lines and press tab to indent the whole block at once,
but that somehow doesn't work now.
It's worth noting that shift+tab works to decrease indent.

**Comment by inducer** [comment]
Was that working at some point?

**Comment by unnat** [comment]
I believe so, while TAing last semester. I think it worked this semester too.
Though this is from the subconscious. I think that is shift+tab works to decrease indent
of multiple lines, tab also should work for increasing code block's indent.

**Comment by inducer** [comment]
I've just updated the Illinois instance. Works for me now. Thanks for the suggestion.

**Comment by unnat** [comment]
Tab works, but now shift+tab is doing some non indent-preserving activity. 
Before:
![before](https://cloud.githubusercontent.com/assets/13321392/22962225/33432536-f311-11e6-927e-ee105de71788.png)
After:
![after](https://cloud.githubusercontent.com/assets/13321392/22962229/39682bf0-f311-11e6-9b30-0645bb5fb12e.png)
