### ISSUE TITLE
Shortest time flow can show up as out of bounds on time histogram due to rounding error

### ISSUE THREAD

**Issue by eecarrier** [inducer/relate#292]
With logarithmic histograms (like time histogram), start of 1st bin is computed as `exp(log(min_value))` which should theoretically evaluate to min_value.  But, in some cases due to rounding error it will evaluate to a number slightly larger than min_value (for example if min_value=10.0) which causes the shortest time flow to incorrectly show up as out of bounds.

**Comment by inducer** [comment]
Thanks for the report! Could you submit a patch/pull request?

**Comment by inducer** [comment]
Thx!
