### ISSUE TITLE
Notice:  ImportError when importing typing.Text for Python3.5 on Windows

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#306]
This is a [known issue](https://github.com/python/mypy/issues/1838#issuecomment-231539004) for python3.5:
> Python 3.5 comes with its own version of typing, which was added before the introduction of typing.Type. ...  Python is picking up the standard library version instead of the version from pip.

My current work around is deleting or renaming the built-in typing.py (at ``%PythonPath%/Lib/typing.py``) .

**Comment by inducer** [comment]
This can be worked around by enclosing the `typing` import with `if False:`.

Important exception: `from typing import cast` needs to be outside of that.

Could you submit a merge request on Gitlab?

**Comment by dzhuang** [comment]
Ok, I'll have a try.

**Comment by dzhuang** [comment]
The how to deal with this [line](https://github.com/inducer/relate/blob/master/course/content.py#L1093)?

**Comment by inducer** [comment]
```
if False:
    from typing import Type
from typing import cast, Text
```

**Comment by dzhuang** [comment]
That will result in ``ImportError: cannot import name 'Text'`. In that [line](https://github.com/inducer/relate/blob/master/course/content.py#L1093), ``Text`` is not solely for mypy test, but is actually used. (Sorry, I should have make it clear. )

**Comment by inducer** [comment]
How about this?
```
if False:
    from typing import Text
    stuff = cast(Text, stuff)
```

**Comment by dzhuang** [comment]
Is this right?
```
datespec_str = datespec
if False:
    from typing import Text
    datespec_str = cast(Text, datespec).strip()
```

**Comment by inducer** [comment]
Maybe leave the code as it is and try the following:

```
try:
    from typing import Text
except ImportError:
    Text = None
```

(`cast` does not consider its first argument when not in the type checker)

**Comment by dzhuang** [comment]
Ok, thanks for the explanation.
