### ISSUE TITLE
FeatureRequest: Permission on viewing participants' name

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#307]
Sometime it's sensitive for some participants to view other participants' name. For example, there are cases where it's not necessary for TA's to knew the name of a participant when doing the grade.

**Comment by inducer** [comment]
That's a good idea. I don't personally have a need, but I am supportive of having this. I'd be happy to take a patch. Initial versions might be a bit leaky--because we show those names in lots of places. (Pick lists for example)

**Comment by dzhuang** [comment]
This [line](https://github.com/inducer/relate/blob/39e894ce4dbb9c7f95761b472901826cbfa99ecf/course/templates/course/gradebook-by-opp.html#L138) seems not working. As ``Participation.role`` has been deprecated, how to determine if a participation belongs to which type? I had thougth it should be in ``constants.py``, but I didn't find it. It seems we can only use ``participation.get_role_desc()`` to get a string desribing that participation? Or use an existing pperm to tell the role?

**Comment by inducer** [comment]
I'd say use a `pperm`.

**Comment by dzhuang** [comment]
Thanks! I think ``pperm.view_gradebook`` is enough to differentiate students from course staffs.
