### ISSUE TITLE
Known bug for Dulwich in Python3.5

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#310]
It raises TypeError("Cannot mix str and non-str arguments") for some ended course on my instance after I upgraded from py2.7 to py3.5. 

The issue had been reported [here](https://github.com/jelmer/dulwich/issues/471). Although the issue is closed, the bug is still there. The weird thing is that the [demo contents](https://github.com/inducer/relate-sample) works well.

**Comment by dzhuang** [comment]
It seem the reason the demo works well because it was using ``SSHGitClient``, the error was raised for ``HttpGitClient``.

**Comment by inducer** [comment]
This seems like an upstream bug. Could you try and reproduce that with the `dulwich` command line client and follow up on the linked bug? Also, if you'd like me or one of the students to take a look, a complete reproduction procedure would help.

**Comment by dzhuang** [comment]
I tested with the following script:

```
from dulwich.client import get_transport_and_path
client, remote_path = get_transport_and_path('https://github.com/inducer/relate-sample.git')

import os
repo_path = os.path.join(os.getcwd(), 'test-repo')
if not os.path.isdir(repo_path):
    os.mkdir(repo_path)

from dulwich.repo import Repo
repo = Repo.init(repo_path)
remote_refs = client.fetch(remote_path, repo)
```

It worked without problem. However, when I add [this lines](https://github.com/inducer/relate/blob/d6d5e49613e470628d5202a5bd96bbea03851eba/course/versioning.py#L174-L177), it produced the error: ``Cannot mix str and non-str arguments``. 

Not knowing why, I commented those lines and tested on my instance, with ``HttpGitClient`` (in the form of https://foo.bar.com/repo.git), ``SSHGitClient`` (in the form of git@foo.bar.com/repo.git plus RSA PRIVATE KEY) and ``TCPGitClient`` (in the form of git://foo.bar.com/repo) all worked well, while keeping those lines gave the error only for ``HttpGitClient``.

**Comment by dzhuang** [comment]
This can be confirmed as an upstream issue. I've created a PR [here](https://github.com/jelmer/dulwich/pull/519).

**Comment by dzhuang** [comment]
I began to  wonder if this is not an upstream bug, when I removed [the lines](https://github.com/inducer/relate/blob/d6d5e49613e470628d5202a5bd96bbea03851eba/course/versioning.py#L174-L177), all things were working well. Did the [commit](https://github.com/jelmer/dulwich/commit/6676b7f6c66a1ec4e352ac3256a62e00b551c165) make those line unnecessary?

**Comment by inducer** [comment]
Thanks for digging into this!

**Comment by dzhuang** [comment]
Simple remove [these lines](https://github.com/inducer/relate/blob/d6d5e49613e470628d5202a5bd96bbea03851eba/course/versioning.py#L174-L177), all things were working well. I think the [commit](https://github.com/jelmer/dulwich/commit/6676b7f6c66a1ec4e352ac3256a62e00b551c165) make those line unnecessary, because ``fetch`` method now accept ``path`` both as ``bytestring`` and ``str``.

**Comment by inducer** [comment]
Confirmed that removing these lines doesn't seem to hurt, at least on `dulwich>=0.17.3`. I've bumped the version requirement accordingly.

**Comment by inducer** [comment]
Thanks again for investigating this.

**Comment by dzhuang** [comment]
Thanks for the fix!
