### ISSUE TITLE
FeatureRequest: more friendly user-defined pages

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#311]
It's too hard to debug user-defined pages in Repo. Can we add some (pages_plugins) settings so that user-defined pages can be easily included and imported?

**Comment by inducer** [comment]
Not sure I understand what you mean--could you explain what your desired user interface would look like?

**Comment by dzhuang** [comment]
For example, add some settings in local_settings like:

```
RELATE_CUSTOM_PAGE = (
    "myCustomApp.pages.myCustomPageType1",
    "myCustomApp.pages.myCustomPageType2",
)
```
where myCustomApp is a django resuable app which should be listed in extra ``installed_apps`` (in local_settings). The above settings is imported in ``course.pages.__init__``, Then those custom page types can be used directly in the repo.

**Comment by inducer** [comment]
You should be able to do just do

```
type: myCustomApp.page.myCustomPageType1
```

in the repo, and it should work. As in, `type:` *should* take any dotted name.

**Comment by dzhuang** [comment]
That cool. Thanks!
