### ISSUE TITLE
Validator(s) in SignUpForm need to be updated

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#313]
Since RELATE dropped support for Django version <1.10, we can/should have alternative [validator(s)](https://docs.djangoproject.com/en/1.10/ref/contrib/auth/#validators) for username. I found this because new users are signing up using Chinese characters on my instance(PY3, Django version1.10). I tested and found the [validator](https://github.com/inducer/relate/blob/d6d5e49613e470628d5202a5bd96bbea03851eba/course/auth.py#L390) failed: *ANY* string can pass validation.

**Comment by dzhuang** [comment]
It seems the MR is merged in gitlab, but not here. If there's any problem with that code, please let me know.

**Comment by inducer** [comment]
Nothing wrong. I just hadn't pushed the changes from one to the other and vice versa.

**Comment by inducer** [comment]
(Should be all better now.)

**Comment by dzhuang** [comment]
Thanks. Then we can close this issue now. Fixed in a96dcc66b73d946d585ed803adca0e0998a46f57.
