### ISSUE TITLE
Submit+next buttons at top in grading interface broken

### ISSUE THREAD

**Issue by inducer** [inducer/relate#331]
(and I just confirmed in different browsers that the submit/nextpage and submit next session buttons do not work)

cc @lukeolson

**Comment by inducer** [comment]
Can confirm that buttons at top are broken in Firefox. Buttons at bottom work.

@dzhuang, this is your change from #314. Could you look into this?

**Comment by dzhuang** [comment]
Sorry. I'll submit a patch ASAP.

**Comment by inducer** [comment]
@lukeolson how soon do you need this on the IL instance?
