### ISSUE TITLE
 RemovedInDjango21Warning: django.utils.translate.string_concat() is deprecated in favor of django.utils.text.format_lazy().

### ISSUE THREAD

**Issue by inducer** [inducer/relate#334]
@dzhuang We should act on that pretty soon, before it becomes a problem.

**Comment by dzhuang** [comment]
It seems this is not so urgent because it was not *removed* in 1.11.1, but I'll look into this.

**Comment by dzhuang** [comment]
This was fixed by 6b35104b7895af481fbf6a49f218df5dc1c191b0 .

**Comment by inducer** [comment]
Thx!
