### ISSUE TITLE
bootstrap3_datetime not compatible with Django >= 1.11

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#335]
```
  File "/var/lib/gitlab-runner/builds/4ec8067d/0/dzhuang/relate/.env/lib/python3.5/site-packages/bootstrap3_datetime/widgets.py", line 128, in render
    input_attrs = self.build_attrs(attrs, type=self.input_type, name=name)
TypeError: build_attrs() got an unexpected keyword argument 'type'
```
According to the [Notes](https://docs.djangoproject.com/en/dev/releases/1.11/#deprecated-features-1-11):

> The signature of private API ``Widget.build_attrs()`` changed from ``extra_attrs=None, **kwargs`` to ``base_attrs, extra_attrs=None``.

**Comment by inducer** [comment]
Fixed by merging https://github.com/inducer/django-bootstrap3-datetimepicker/pull/1. Thanks for working on this!
