### ISSUE TITLE
Feature: Hide Institutional ID and/or Editor forms in profile

### ISSUE THREAD

**Issue by dfrdmn** [inducer/relate#340]
We are setting up RELATE (awesome btw!) and have no need for the institutional ID or editor parts of the profile. As a quick fix to reduce confusion with users, we are simply hiding the layouts by creating two settings:

    RELATE_SHOW_INST_ID_FORM = False
    RELATE_SHOW_EDITOR_FORM = False 

We appended the `adjust_layout` function by adding to display/hide based on these settings:

    if not settings.RELATE_SHOW_INST_ID_FORM:
        self.helper.layout[1].css_class = 'well hidden'
    if not settings.RELATE_SHOW_EDITOR_FORM:
        self.helper.layout[2].css_class = 'well hidden'

This seemed like the most straightforward approach to ensure that no form validation breaks along the way. If you think this is worthwhile, I can create a pull requestor modify it per your needs and then create the request.

**Comment by inducer** [comment]
I'd be happy to have both of those as settings.

**Comment by inducer** [comment]
(Also, happy to hear you're liking RELATE!)
