### ISSUE TITLE
process_yaml_for_expansion failure in SandBox

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#344]
For the following markup:

```
    type: Page
    id: vectors
    content: |

        # Vectors

        A vector is pretty straight.
```
The [`process_yaml_for_expansion`](https://github.com/inducer/relate/blob/master/course/content.py#L394) method returns

```
    type: Page
    id: vectors
{% raw %}
    content: |

        # Vectors

        A vector is pretty straight.

{% endraw %}
```

while in sandbox, it returns:
```
type: Page
id: vectors
content: |

    # Vectors

    A vector is pretty straight.
```
i.e., in sandbox, the ``content`` block was not wrapped by {% raw %}{% endraw %}, which sometimes will cause failure  for debugging in sandbox. See #343 

For the reason, each line has a trailing "\r" for the text pasted in sandbox, that cause ``YAML_BLOCK_START_SCALAR_RE `` failed to match the block start line.

**Comment by inducer** [comment]
Fixed by https://gitlab.tiker.net/inducer/relate/merge_requests/28/commits, specifically df4335fd26068b56b013b01d4fab513a340107cf. Thanks, @dzhuang!
