### ISSUE TITLE
Support git ssh

### ISSUE THREAD

**Issue by samtux** [inducer/relate#347]
It is possible to add a repository without the GIT protocol, ie with git://<repository>?. I have several private repositories  with GIT SSH, of the form git@gitlab.com:aulageo/curso.git and it does not work. 

The following error is reported:

`Course creation failed: TypeError: git-upload-pack 'aulageo/curso.git'`

What can I do to solve this problem?

Thanks.

**Comment by inducer** [comment]
Git via SSH is supported, I use that all the time. Python 2 or 3? What version of dulwich?

**Comment by samtux** [comment]
@inducer, the version of python is 2.7.

**Comment by inducer** [comment]
Thanks for reporting this--this had indeed bitrotted. Should be fixed in latest git.
