### ISSUE TITLE
Follow-up to 63afcc4e

### ISSUE THREAD

**Issue by inducer** [inducer/relate#351]
@dzhuang In 63afcc4e, you added code to update `prev_visit_id` in the flow page POST code path. That code just broke on our production instance. It's not guaranteed that `prev_answer_visits` is non-empty after `post_flow_page`. For instance, the form may not have successfully validated. I responded with c13c371, but I wanted to make sure that I'm not in turn re-breaking the submission history dropdown in this corner case.

Could you take a look? Thanks!

**Comment by dzhuang** [comment]
Sorry for late response! I think that's the fix.

**Comment by inducer** [comment]
So the JS code is OK if `prev_visit_id` is `None`?

**Comment by dzhuang** [comment]
Sure, I've manually tested that just now.

**Comment by inducer** [comment]
Great. Thanks for following up. Looks like we can close this then.
