### ISSUE TITLE
Feature: allow non-superuser instructors to edit events (kind of urgent)

### ISSUE THREAD

**Issue by ifaintad** [inducer/relate#361]
An instructor has no way/permission to view events he've just created, let alone edit, except that he is granted superuser permissions of the site (solely staff is not enough).
Can you solve the problem? I think it's reasonable to assume non-superuser instructors should have partial permissions for admin though not full control.

**Comment by inducer** [comment]
There's a merge request/branch for that:

https://gitlab.tiker.net/inducer/relate/merge_requests/42

I have not yet had the time to review it, but you could likely just merge that for your local instance.

**Comment by inducer** [comment]
Closing because it's a duplicate of #322.

**Comment by ifaintad** [comment]
Thank you!

**Comment by dzhuang** [comment]
Just find I was using a testing account to report this. Thanks again.

**Comment by inducer** [comment]
And here I was, all excited that another user showed up out of the woodwork. ☺

**Comment by dzhuang** [comment]
You are so modest! :joy:
