### ISSUE TITLE
Datetime picker issue

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#362]
For form with multiple datetime picker widget (new course page and edit course page), only first picker worked. I'm using Django 1.10.7, not sure if Django1.11 worked @inducer .

I report it here because the source repo is not maintained and we are using the patched fork. I'm quite sure the reason is my [patch](https://github.com/inducer/django-bootstrap3-datetimepicker/commit/2c5d853df4d4795e1dfc3950e8e5d797f2436c77#diff-1417bc7e3bc264c256d3c015cd9190bf).

We might have to test this one: https://github.com/jsanchezislas/django-bootstrap3-datetimepicker/commit/e147ebe1c3d4726613b3551b2b846bba7c100e4a

**Comment by dzhuang** [comment]
A temp workround:  [here](https://github.com/dzhuang/relate/commit/03e975648aff5dc5c2f03b032beb614d5c497009)

**Comment by inducer** [comment]
I'm open to switching to the jsanchezislas one. Could you test it and submit a PR?

**Comment by dzhuang** [comment]
Ok. But I didn't have time to test that right now. Perhaps this weekend.

**Comment by dzhuang** [comment]
One question, which version of Django your are using right now? If it's 1.11.x, can all widgets in setup new course page and edit course page working correctly?  @inducer

**Comment by dzhuang** [comment]
My tests failed. One of the issue was metioned by https://gitlab.tiker.net/inducer/relate/merge_requests/42
> I discovered that the issue is caused by the removal of the `size()` function in the recent update of jquery.

and https://github.com/nkunihiko/django-bootstrap3-datetimepicker/pull/58

**Comment by dzhuang** [comment]
Fixed by https://github.com/inducer/django-bootstrap3-datetimepicker/pull/3

**Comment by inducer** [comment]
Merged above PR, verified fix. Thank you!
