### ISSUE TITLE
DEFAULT_FROM_EMAIL is undocumented

### ISSUE THREAD

**Issue by inducer** [inducer/relate#363]
@dzhuang It looks like `Course.get_from_email` uses `settings.DEFAULT_FROM_EMAIL`, but that setting doesn't occur in either `relate/settings.py` or `local_settings.example.py`, so it's not very discoverable and likely to lead to errors when users need to set up From-restricted email.

Could you take a look?

**Comment by dzhuang** [comment]
Sorry, it's my fault. I'll submit a PR/MR along with tests to fix it.
