### ISSUE TITLE
Is that a bug: unconfirmed users can request enrollment for courses in some cases

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#369]
It happens when a course does not require email suffix, I found this when writing tests.

**Comment by inducer** [comment]
An unconfirmed user would (as far as I know) never be logged in, so I think it's more  a theoretical issue. But it can't hurt to add a check.

**Comment by dzhuang** [comment]
I managed to do that by manually changing an active user to be unconfirmed in admin. That's rare of cause.

**Comment by dzhuang** [comment]
It's checked here, when the course requires email suffix. https://github.com/inducer/relate/blob/master/course/enrollment.py#L190

**Comment by inducer** [comment]
Sure--could you just kill the first half of that conditional?

**Comment by dzhuang** [comment]
Sure, with tests.
