### ISSUE TITLE
Raw passthrough for Jinja + Markdown

### ISSUE THREAD

**Issue by inducer** [inducer/relate#373]
```
{% raw %}
...
{% endraw %}
```

doesn't currently work, because that's already used by YAML-level block literal escaping. This should be fixed, by escaping any `{% endraw %}`s found inside of block literals.

**Comment by davis68** [comment]
I infer that the relevant code in this case is [`relate/content.py:process_yaml_for_expansion`](https://github.com/inducer/relate/blob/master/course/content.py).  It's not clear to me what `yaml_block_scalar_match` is checking for in that context though.  Is that the correct block to escape within for Jinja?

**Comment by inducer** [comment]
Yeah. What's happening there is that whenever Relate processes yaml, it looks for block literals (like blocks of markup or code or some such):

```
content: |

    # Fun headline

    Text stuff

value: 13123
```

and turns that into

```
content: |
{% raw %}

    # Fun headline

    Text stuff

{% endraw %}
value: 13123
```

so that the block literal gets left alone by Jinja. Relate markup processing applies its own round of Jinja expansion, so this didn't happen, then the block literal would get expanded twice, with... probably weird results. Now if you use `{% endraw %}` inside of the block literal, Jinja gets super confused because the raw block ends sooner than intended. In particular, it hits another `{% endraw %}` at the intended end of the block literal. A solution to this would be to pick a string that does not occur in the snippet of YAML (randomly generated number goop works well--just keep adding characters if the string is in there) and replace any `{% endraw %}` in the block literal with `{% 239041723472endraw %}`. Then do the YAML expansion. Then undo the replacement. Ta-dah, properly nestable raw blocks.

**Comment by davis68** [comment]
I'm preparing a PR to deal with this.

Is it preferred to handle this replacement once, by lines 399 and restoring at 451, or is that too risky because we're not sure where the endraws are yet?  Else we could handle it before line 436 and restore after line 440.

**Comment by inducer** [comment]
Hmm, upon closer inspection, it doesn't look like we really have a chance to undo the replacement of `{% 239041723472endraw %}`, because `process_yaml_for_expansion` gets called from multiple sites, not all of which necessarily allow us to do that. Instead, I suspect we might be able to get away with simply replacing `{% endraw %}` within a block literal with `{% endraw %}{{ '{% endraw %}' }}{% raw %}`.
