### ISSUE TITLE
Runpy Dockerfile outdated

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#377]
It seems the latest source in the i386 image was using Py3.6.3  for `python3`, which do not allow import module with [this line](https://github.com/inducer/relate/blob/master/docker-image-run-py/runpy#L32).

**Comment by dzhuang** [comment]
It raises `ImportError: attempted relative import with no known parent package`

**Comment by inducer** [comment]
What specifically are you doing that leads to this error?

**Comment by dzhuang** [comment]
```
root@iZwz9ermkjlnruem8ofov7Z:~# docker run -it dzhuang/relate
WARNING: IPv4 forwarding is disabled. Networking will not work.
root@45d474b2b208:/# cd opt/runpy
root@45d474b2b208:/opt/runpy# python runpy
bash: python: command not found
root@45d474b2b208:/opt/runpy# python3 runpy
Traceback (most recent call last):
  File "runpy", line 32, in <module>
    from code_runpy_backend import Struct, run_code, package_exception
  File "/opt/runpy/code_runpy_backend.py", line 31, in <module>
    from .code_feedback import Feedback, GradingComplete
ImportError: attempted relative import with no known parent package
```
(P.S., I was using docker hub automated build, by copying code_feedback.py and code_runpy_backend.py into docker-image-run-py, see [my branch](https://github.com/dzhuang/relate/tree/docker_hub_build/docker-image-run-py))

With your build:
```
root@iZwz9ermkjlnruem8ofov7Z:~# docker run -it inducer/relate-runpy-i386
WARNING: IPv4 forwarding is disabled. Networking will not work.
root@45eaeeb26430:/# cd opt/runpy
root@45eaeeb26430:/opt/runpy# python3 runpy
STARTING, LISTENING ON 9941
```

**Comment by dzhuang** [comment]
The difference is the version of Python3, my build is using 3.6.3, and your build was using 3.5.3.

**Comment by inducer** [comment]
Thanks for reporting this.
