### ISSUE TITLE
It won't raise expected error when nestedly use course_view decorator

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#395]
https://github.com/inducer/relate/blob/63a25b66a45dd2e50dab30124da2a91e4fec14e0/course/utils.py#L683

If I decorate https://github.com/inducer/relate/blob/63a25b66a45dd2e50dab30124da2a91e4fec14e0/course/utils.py#L845 with `course_view`, it just failed with 404, not the expected error.

The `_is_in_context_manager` are unknow to each other in different `CoursePageContext` instances..

**Comment by dzhuang** [comment]
Can we add an attribute `_is_in_context_manager` to the HttpRequest object (i.e., `pctx.request`) instead?

**Comment by inducer** [comment]
I don't understand what the problem is. Could you explain?

**Comment by dzhuang** [comment]
In short, I can't find a situation that could trigger the exception.

**Comment by inducer** [comment]
If you do

```
with ...:
   with ...:
      pass
```

that should raise, no?

**Comment by dzhuang** [comment]
I tested with:
```python
@coures_view
def func_a(pctx):
     ...
    return fuc_b(pctx)


@course_view
def func_b(pctx):
    ...

```
It's doesn't raise the expected `RuntimeError()`,  a  `404` instead.

**Comment by inducer** [comment]
But each decorator creates a new `CoursePageContext` instance. I'm not surprised that doesn't raise.

**Comment by dzhuang** [comment]
It's also the case for context manager, am I right?

**Comment by inducer** [comment]
It can be, but it doesn't have to be. This form will make new instances (and hence won't conflict):

```
with CoursePageContext(...) as cpc:
   with CoursePageContext(...) as cpc2:
      pass
```

but this will:


```
cpc = CoursePageContext(...)
with cpc:
   with cpc:
      pass
```

It's perhaps an unlikely scenario to defend against, but I just don't like code that has the potential to be silently incorrect. (and it's easy to get into that situation if you're modifying state)

**Comment by dzhuang** [comment]
Got it. Thanks for the explanation.

**Comment by dzhuang** [comment]
Todo: add tests for this part.

**Comment by dzhuang** [comment]
Tested by #535 , closing.
