### ISSUE TITLE
Demo Instance?

### ISSUE THREAD

**Issue by orsenthil** [inducer/relate#396]
* Do you have demo instance of relate ?
* Is the idea the users will try the local installation for demo?

**Comment by inducer** [comment]
> Do you have demo instance of relate ?

I would like to, but I don't currently have the time to provide and maintain one.

> Is the idea the users will try the local installation for demo?

Sure, that is probably the next-best option. I try hard to keep the install procedure quick and manageable by keeping heavier-weight/non-pip dependencies (memcached, celery) mostly optional.

Thanks for the suggestions though.
