### ISSUE TITLE
Bug: weid behavior when signout

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#399]
Anonymous user see "you've already signed in".

**Comment by dzhuang** [comment]
I've also see some related views and templates can be optimized, including `profile` and `sign_out` views.

**Comment by dzhuang** [comment]
@inducer I find there are built-in [login](https://github.com/django/django/blob/master/django/contrib/auth/views.py#L37) and [logout](https://github.com/django/django/blob/master/django/contrib/auth/views.py#L104) views (CBV), do you accept replace the current views with subclass of the Django built-in views?

**Comment by inducer** [comment]
If it doesn't lose any functionality, I'd in principle be OK with it. In particular SAML2 will need to continue to work.

**Comment by dzhuang** [comment]
I agree. I'll first fix and test current code before switching to the cbv style.
