### ISSUE TITLE
Bug: institutional_id can't be empty when saving profile form

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#406]
It raises "field is required" or "input not matched". Why that bug had not been reported before?

**Comment by inducer** [comment]
My users can't edit their institutional ID--it comes from SAML2.

**Comment by dzhuang** [comment]
But why that didn't happen to me before, I'm curious, and I can't find the reason even after blame.

**Comment by dzhuang** [comment]
> My users can't edit their institutional ID--it comes from SAML2.

The did you tried to update your own profile? I guess you don't need/ have a institutional ID. If that's the case, it would fail.

**Comment by inducer** [comment]
Guessed correctly: I don't have one.

**Comment by dzhuang** [comment]
Then can you reproduce that bug?

**Comment by inducer** [comment]
Yes, I can reproduce that.

**Comment by dzhuang** [comment]
Thanks for the feedback.
