### ISSUE TITLE
Issue when a tutor is sending emails

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#41]
If the tutor's email address (in the course configuration page) is different with ``SERVER_EMAIL`` in ``settings.py``,  sending an email by the tutor (e.g., sending enrollment decision) will give an error ``mail from address must be same as authorization user``. 

I have no idea whether this is the problem with my email service, or should there be some settings that the tutor should configure his email service.

**Comment by dzhuang** [comment]
See http://stackoverflow.com/questions/20293986/how-do-i-send-email-from-a-users-email-address-with-django

It seems to be technically difficult to enable multiple tutors with different email address as sender on the website.

Maybe we can set a default email address to send notifications to users, and for some specific emails, e.g., enrollment decision, or feedback of exercise, add the tutors' email as the ``reply-to`` header so that students can communicate with tutor directly.

**Comment by inducer** [comment]
For my courses, I made a policy decision that the students should not be aware who graded their work. But it would certainly be possible to include a 'cc me' box (or a corresponding course-wide setting). I'd be happy to take a patch.

**Comment by dzhuang** [comment]
So do you mean you agree that ``course.from_email`` can not be set as a sender if it is not the same as the ``server_email``?

**Comment by inducer** [comment]
No, I don't think I'm saying that--it should be possible to set it to anything you like.

**Comment by dzhuang** [comment]
When I use different email addresses (``course.from_email="foo@domain1.com"``, settings.SERVER_EMAIL="bar@domain2.com``), I got an internal server error ``mail from address must be same as authorization user`` when I send an enrollment decision email to students. What the problem?

**Comment by dzhuang** [comment]
Maybe it's the problem of my mail service provider.

**Comment by inducer** [comment]
I'd imagine so.

**Comment by dzhuang** [comment]
Thanks.

**Comment by dzhuang** [comment]
The issue was solved when I use gmail as the site email. Now I have to use email other than gmail, as gmail is 404 in some country where I set up my server. I realize that most email service here do not allow sender to have a different email than the site email. There should be an option in the settings so that . I'll try to make a patch.

**Comment by inducer** [comment]
Sounds good, will be happy to take it.
