### ISSUE TITLE
Any idea on how to implement multi text question?

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#43]
Multiple text_input box embedded in a paragraph? I have no idea how to do it. Any suggestions? Thanks.

**Comment by inducer** [comment]
I imagine you would define a Django form as usual. Then you can override the following method:

http://documen.tician.de/relate/flow.html#course.page.PageBase.form_to_html

and instead of the default form rendering produce HTML for a paragraph of text with the form input fields interleaved.

**Comment by dzhuang** [comment]
As it need full understanding of crispy form, bootstrap, I find it hard for me to implement this in a short while. It might be better waiting for your progress :).

**Comment by inducer** [comment]
I don't really have a need for that type of interaction, so this may turn out to be a longer wait than you were hoping. :)

That said, I think crispy would mainly just be in the way trying to implement this. I would suggest just using bare Django forms with hand-(template-?)generated HTML. And for that you don't really need to understand Bootstrap either--just mimic what crispy generates for other forms.

**Comment by inducer** [comment]
Looks like this is done. :+1:
