### ISSUE TITLE
Which image file formats are supported?

### ISSUE THREAD

**Issue by adamjstewart** [inducer/relate#439]
I would like to embed a vectorized image file, like SVG or PDF, in a homework flow. Rumor has it that PDF doesn't work, and I haven't tried SVG yet. I don't see anything in the documentation that mentions which image file formats are supported.

**Comment by inducer** [comment]
It's really "whatever the browser supports". Relate doesn't really impose any additional restrictions. (*)

(*) If [this code](https://github.com/inducer/relate/blob/4280e1829a741680f3e062fb4952b2fe37f6c7fb/course/views.py#L358) doesn't guess the right MIME type, then some additional work might be needed.
