### ISSUE TITLE
Impose deadline (expire sessions) stuck on pending

### ISSUE THREAD

**Issue by eecarrier** [inducer/relate#444]
When selecting "Impose deadline (expire sessions)" for all participants (modify many sessions at once), the progress bar hangs and simply says "Pending", never updating.  

If you let it run for a while, the sessions all get ended, so behind the scenes, it appears as if they are ending without an issue and the issue appears to be limited to progress bar/update message.

**Comment by inducer** [comment]
Continued here, since it's more of an issue with the operation of the UIUC instance than Relate itself:

https://gitlab.tiker.net/teaching/relate-uiuc-operations/issues/1
