### ISSUE TITLE
Grade points displayed conflicts with percentage (rounding issue)

### ISSUE THREAD

**Issue by eecarrier** [inducer/relate#449]
In the gradebook, the points displayed can conflict with the percentage due to rounding in the displayed value.  So, for instance, if a student's actual grade is 10.75/12.0, it will display 10.8/12.0 points (inaccurate), but will display 89.6% (accurate).  However, this is confusing to students as it is unclear to them which is correct.

**Comment by inducer** [comment]
What do you suggest should be done? Display up to 2 digits? 4? all of them?

cc @dzhuang -- I think you may have last touched that display code.

**Comment by dzhuang** [comment]
What if 89.996% for 2 digits and 89.99996 for 4 digits?
Or,   `<span title="89.583333">90%</span>?`

**Comment by dzhuang** [comment]
Oh, I was wrong. It's about the points, not the percentage. I'm ok for more digits.

**Comment by dzhuang** [comment]
@eecarrier Can you confirm #451 worked as expected?

**Comment by eecarrier** [comment]
@dzhuang Due to some local system issues, I don't have a running relate instance at the moment.  But displaying 2 digits, which is what it looks like the commit does, would be great.
