### ISSUE TITLE
May not use GET for state change

### ISSUE THREAD

**Issue by inducer** [inducer/relate#458]
https://github.com/inducer/relate/commit/b829292613cff4069c1d674cb5759d6238d8cb2e#commitcomment-27536731

cc @dzhuang

**Comment by inducer** [comment]
To explain this in a bit more detail: Web infrastructure (browsers, proxies, ...) are allowed to make GET requests independent of user action (for caching, page preloading, any number of reasons), because there's a documented assumption that they do not change state. Therefore *any* state change *must* use POST. GET requests may appear to work at first, but they inflict breakage later that becomes hard to track down.

Note that I'm not against making 'stop impersonate' more convenient--that's a perfectly legitimate goal. I just think it can be done without violating the HTTP standard.

**Comment by dzhuang** [comment]
Just see this, I'll revert that tomorrow.

**Comment by dzhuang** [comment]
Done. Sorry for that.

**Comment by inducer** [comment]
b999187dcb916f3e2436ef8702ab31b0e169af0b
