### ISSUE TITLE
Inline questions do not render properly on mobile devices

### ISSUE THREAD

**Issue by inducer** [inducer/relate#49]
Leftover from #48

**Comment by dzhuang** [comment]
Not a bug. This is the result with bootstrap inline forms, that a punctuation (comma, period or question mark) following a form field will look like leading a new paragraph, on mobile devices with screen width no more than 767px. 

To remove the unwanted punctuation from the form, we can wrap those punctuations with some element tag which won't be shown for small devices. I'll add docs to ``InlineMultiQuestion`` latter.
