### ISSUE TITLE
DataTable i18n not working as expected

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#491]
@ishitatsuyuki  According to https://github.com/DataTables/Plugins/pull/192, the lang files contains comments and the reponse are not json. So i18n of DataTable is not working as expected.

**Comment by dzhuang** [comment]
Also, see https://datatables.net/forums/discussion/26977/i18n-plugin-files-are-not-in-json-format

**Comment by ishitatsuyuki** [comment]
To workaround, we possibly could link to the CDN versions mentioned in that issue.

**Comment by dzhuang** [comment]
I think `pycountry` is a little heavy for this functionality. I'd rather cook a new repo with  npm to solve that.

**Comment by JonGarbayo** [comment]
For me (on 1.10.15 version), "not working as expected" is not really accurate: it's not working at all, every string stays in English.

@dzhuang, did you created a public npm repo with that problem fixed :) ?

**Comment by dzhuang** [comment]
@JonGarbayo Did you see this commit (https://github.com/inducer/relate/commit/70480453a5f37ecf414cde8650ef6d9ebd75a935) which closed this issue,

**Comment by JonGarbayo** [comment]
Oh I am really sorry: I landed here searching for a fix for that not working Datatables .lang files, but I didn't see I was not on a Datatables GitHub repo 😅

I don't use relate, so I am not aware of the state of the problem here, sorry.

**Comment by dzhuang** [comment]
@JonGarbayo It's ok. And I think our fix might be helpful for you.
