### ISSUE TITLE
Improve structure of main page

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#54]
For example, ``available``, ``in progress``, ``ended``，only ``avaiable`` courses are shown on main page, and only participants and see ``in progress`` and ``ended`` course.

**Comment by inducer** [comment]
I've gone ahead and renamed this bug report to serve as a point of discussion for how to improve the structure of the main page. We are actually encountering the same problem with our relate instance at Illinois. There's something like six courses in that list right now, and it is starting to get messy. At the very least, the list should be sorted in some manner, and I agree that some indication of what courses lie in the past is probably also going to be useful.

I don't think I would want the system to impose some sort of policy over what courses are or are not shown on the main page. I think it would be easy enough to just check or uncheck the "show on main page" checkbox on a course-by-course basis that no definite policy is needed.

But I do agree that it would likely be useful for the system to know about course start and end dates (or maybe a notion of course status).

**Comment by dzhuang** [comment]
I've tried to do it in [PR55](https://github.com/inducer/relate/pull/55), maybe it's not the best way, waiting for your improvement.
