### ISSUE TITLE
AssertionError in test_two_mime_types_normalize

### ISSUE THREAD

**Issue by inducer** [inducer/relate#562]
https://gitlab.tiker.net/inducer/relate/-/jobs/48961 has a failure with 9f8ea348:

```
======================================================================
FAIL: test_two_mime_types_normalize (tests.test_pages.test_upload.UploadQuestionNormalizeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/gitlab-runner/builds/1f7ecaef/0/inducer/relate/tests/test_pages/test_upload.py", line 224, in test_two_mime_types_normalize
    ensure_download_after_grading=True, dl_file_extension=".dat")
  File "/var/lib/gitlab-runner/builds/1f7ecaef/0/inducer/relate/tests/base_test_mixins.py", line 2196, in submit_page_answer_by_page_id_and_test
    file_with_ext_count=dl_file_with_ext_count)
  File "/var/lib/gitlab-runner/builds/1f7ecaef/0/inducer/relate/tests/base_test_mixins.py", line 2029, in ensure_download_submission
    assert len([f for f in zf.filelist if
AssertionError

----------------------------------------------------------------------
```

Confusingly, CI on Github seems to be OK. @dzhuang Any idea what the problem might be?

**Comment by dzhuang** [comment]
That's testing this part https://github.com/inducer/relate/blob/0678467141f7e143bf29690a5f16d8335545fb6f/course/page/upload.py#L255-L269

with this as the mocked page for page_id `proof`:
https://github.com/inducer/relate/blob/0678467141f7e143bf29690a5f16d8335545fb6f/tests/test_pages/test_upload.py#L131-L149

With a pdf file submit as answer. That used to work well, and then about yesterday, I've met the same problem like your when testing on APPVEYOR-CI, never on TRAVIS-CI. Sometimes for a second run, that failure will run away. I've no idea why currently.

**Comment by dzhuang** [comment]
I'll add message to see the the actually file list in the zipped file.

**Comment by dzhuang** [comment]
The expected file name is `test_student.dat`, while it got 'test_student.pdf'. See https://gitlab.tiker.net/inducer/relate/-/jobs/48976

**Comment by inducer** [comment]
Thanks for taking care of this!

**Comment by dzhuang** [comment]
You're welcome! FYI, I think the reason for the fail was previous mock trick was not acting as expected because of cache.
