### ISSUE TITLE
FeatureRequest: Editing interface

### ISSUE THREAD

**Issue by solomonik** [inducer/relate#582]
Motivated by existing features, would it be possible/difficult to develop an interface that permits the user to enter 'editing mode' for a flow question that just looks like a page sandbox with that question source but also permits launching a commit pull-request to the hosting git repository (or just pushing to a given buffer repo)?

My major motivation for this is to provide an interface that enables efficient editing and creation of questions without full access to the repository.

**Comment by inducer** [comment]
Dupe of #70. See also https://gitlab.tiker.net/inducer/relate/merge_requests/62. :)

**Comment by inducer** [comment]
(And, in case that's not clear, I totally agree.)

**Comment by inducer** [comment]
One interesting point is that it sounds like you have a more sophisticated permission model in mind. That's potentially easy to include in the design if you provide design feedback now, compared to bolting it on later.
