### ISSUE TITLE
Figure out visibility logic for users/participations

### ISSUE THREAD

**Issue by inducer** [inducer/relate#599]
@dzhuang In 925d0531c, you added this logic:

https://github.com/inducer/relate/blob/a10d9309bfdf68389e4eeaa6ad76485e82b5fa17/accounts/admin.py#L128-L145

Could you explain what the use case guiding this logic was? (I'm not sure I even understand what's going on.) For us at Illinois, the previous logic worked better--we're generally OK with folks that can access the admin seeing everything/everyone related to courses they're associated with.

cc @eecarrier

**Comment by dzhuang** [comment]
I'm ok with your logic. So the problem is: should we include superuser/staff in the queryset? (Sorry for late response).

**Comment by inducer** [comment]
> A further question is: should we include superuser/staff in the queryset? (Sorry for late response).

* Superuser as someone who sees everything I think makes sense.
* I don't think it's relevant to non-staff users--they can't get into the admin anyhow.

**Comment by dzhuang** [comment]
Sorry, am I wrong? I think that queryset is a list of user the request user see in the list view? If I'm right, is it ok for staffs to see superuser/other staffs in the list (and maybe able to modify them? I don't know).

**Comment by inducer** [comment]
> Sorry, am I wrong? I think that queryset is a list of user the request user see in the list view? If I'm right, is it ok for staffs to see superuser/other staffs in the list (and maybe able to modify them? I don't know)?

Oh, sorry. I misunderstood you. From my perspective, yes. If someone has admin access, they *have* to be in a somewhat trusted position, so they're allowed to see everything. (They can anyway if they really want to--the admin access controls are not at all watertight. That's why admin access will have to go eventually.) The view restrictions are there mainly for convenience and to reduce confusion.
