### ISSUE TITLE
Create recurring event: cannot leave ordinal unspecified twice

### ISSUE THREAD

**Issue by inducer** [inducer/relate#603]
For example:

* Create 20 weekly events `office_andreas`, leaving the ordinal unspecified, from (say) a Wednesday at 3:30pm
* Create 20 weekly events `office_andreas`, again leaving the ordinal unspecified, from (say) a Friday at 3:30pm
* "An event with this kind, ordinal, and course already exists." (Paraphrasing from German.)

@dzhuang I distinctly recall that this worked at some point...

**Comment by dzhuang** [comment]
P.S., you seemed to agree [ordinal-less events should be unique](https://github.com/inducer/relate/blob/master/course/models.py#L346-L353) in 32b4578236bbd820a04a39594bb80ec0c23dff67.

**Comment by dzhuang** [comment]
Sorry, I misunderstood you. You meant that there should be no error, and the starting ordinal of the events should be incremented by 10.

Maybe it's because you've changed the `IntegrationError` to `ValidationError` when saving ordinal-event in 32b4578236bbd820a04a39594bb80ec0c23dff67?

**Comment by dzhuang** [comment]
OIC, there reason is https://github.com/inducer/relate/blob/18be12e5c798eb664e105e1ba7da071008c3e00c/course/calendar.py#L149 , for non English lang, the condition will fail. I'll try to fix that.

**Comment by inducer** [comment]
> Sorry, I misunderstood you. You meant that there should be  no error, and the starting ordinal of the events should be incremented  by 10.

Yep, exactly. Thanks for working on this!
