### ISSUE TITLE
Students are able to enroll without approval

### ISSUE THREAD

**Issue by inducer** [inducer/relate#608]
https://github.com/inducer/relate/blob/b0e64c93799cb8b603880f13d5d2c07f4117d06a/course/enrollment.py#L251-L267

Looking at the code in the enrollment view, it looks like students are able to enroll without approval as long as their email suffix matches. This is causing some operational disruption on our end.

@dzhuang Since you were the last one to touch the code, could you explain?

cc @eecarrier

**Comment by dzhuang** [comment]
Sorry, I took it for granted that email suffix match doesn't need manually approval. My bad!
