### ISSUE TITLE
Assertion failure in InlineMultiQuestion

### ISSUE THREAD

**Issue by inducer** [inducer/relate#609]
Just got this traceback:

```
Traceback:

File "/home/andreas/my-relate-env3/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  35.             response = get_response(request)

File "/home/andreas/my-relate-env3/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  128.                 response = self.process_exception_by_middleware(e, request)

File "/home/andreas/my-relate-env3/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  126.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "./course/utils.py" in wrapper
  792.             response = f(pctx, *args, **kwargs)

File "./course/flow.py" in view_flow_page
  1983.                 answer_data, grade_data)

File "./course/page/inline.py" in correct_answer
  862.                     .get_correct_answer_text(page_context)

File "./course/page/inline.py" in get_correct_answer_text
  358.         assert unspec_correct_answer_text

Exception Type: AssertionError at /course/cs101-fa18/flow-session/427261/6/
```

Looking at the code:

https://github.com/inducer/relate/blob/b0e64c93799cb8b603880f13d5d2c07f4117d06a/course/page/inline.py#L352-L358

it is not clear to me how that can happen, especially given the check immediately above that:

https://github.com/inducer/relate/blob/b0e64c93799cb8b603880f13d5d2c07f4117d06a/course/page/inline.py#L338-L345

@dzhuang, any idea?

FWIW, I've asked the TA in question to supply details if he has them.

**Comment by dzhuang** [comment]
`unspec_correct_answer_text` is not `None` but `0` ? Will `assert unspec_correct_answer_text is not None` be a workround?

**Comment by inducer** [comment]
Yeah, I imagine that's it. (and not just a workaround--an actual fix!)

#613

**Comment by inducer** [comment]
Thanks for your help!

**Comment by dzhuang** [comment]
You are welcome. Actually I was just guessing that's a fix, because I failed to reproduce the error.
