### ISSUE TITLE
Migration to Bootstrap 4?

### ISSUE THREAD

**Issue by josh-byster** [inducer/relate#616]
Hi, I was wondering if you were looking to migrate over to Bootstrap 4 now that it's not in alpha/beta anymore. I saw that `CRISPY_TEMPLATE_PACK` is using `bootstrap3` and it [looks like](https://django-crispy-forms.readthedocs.io/en/latest/install.html) it would be straightforward to upgrade. But I'm not sure if there's compatibility issues in terms of styling.

**Comment by inducer** [comment]
This should definitely happen. One potential issue is that references to Bootstrap 3 styling have "leaked" into course content on our end. So from my perspective, it would be the most convenient to make this transition (i.e. merge a relevant PR) at a semester boundary, i.e. at the end of the year or over the summer, so as to not randomly make course content look less pretty randomly in the middle of the semester.

cc @davis68 @dzhuang @lukeolson  -- opinions?

**Comment by davis68** [comment]
Here is the change log for quick reference.  https://getbootstrap.com/docs/4.0/migration/

Notably, buttons need %s/btn-default/btn-secondary/g.  Input forms have some changes as well.

My custom CSS will need some minor changes to class names to be compliant, but no major shovel work.

**Comment by davis68** [comment]
fwiw, I've gotten 101 ready for this transition now. (fingers crossed)

**Comment by inducer** [comment]
It's been a while, but #892 (which is pretty close to done) should get us onto Bootstrap 5.

**Comment by dzhuang** [comment]
I'm ok with it. My fork is more than 100 commit behind yours, and I'll find time to catch up.
