### ISSUE TITLE
Grade opportunity name is not changed when flow title is modified.

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#66]
As the title specifies.

**Comment by inducer** [comment]
If it bothers you, I would be happy to take a patch. This is where that check (and the corresponding update) should probably happen:

https://github.com/inducer/relate/issues/66

**Comment by dzhuang** [comment]
Thank you, I found that position before, but I think my fix might have defect in that it will only be updated when a new session is started. https://github.com/inducer/relate/pull/68

**Comment by dzhuang** [comment]
Partly fixed by 063baf722e6ba8987ae9ea7d9c06502f95c19de8
