### ISSUE TITLE
Better handling for SyntaxError

### ISSUE THREAD

**Issue by davis68** [inducer/relate#680]
Python proper can't catch SyntaxError, but we can filter the Docker output and at least generate a zero.  The current behavior blocks the grade from generating; this would still allow an overall grade.

**Comment by inducer** [comment]
> Python proper can't catch SyntaxError

It can as far as I know? I just tried submitting something with a syntax error, and it generated a grade of zero. Could you be more precise?

**Comment by davis68** [comment]
Drilled down more—I interpreted the result incorrectly.  It was a perms setting that was blocking that grade, not the SyntaxError.
