### ISSUE TITLE
page_data -> page_data.data?

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#695]
https://github.com/inducer/relate/blob/90ca3853fdaf33312c36a2a6c8356068bac8e00d/course/grading.py#L286-L289

I think line 287 might be
```python
         fpctx.page_context, fpctx.page_data.data, 
```
Am I right? (Wondering why it was not tested)

**Comment by inducer** [comment]
I think you're right. The reason it did not fail in tests is because `ChoiceQuestion` is the only question type that uses this data, and that's never human graded.

**Comment by inducer** [comment]
#698

**Comment by inducer** [comment]
Thanks for the report!

**Comment by dzhuang** [comment]
Thanks for the fix!
