### ISSUE TITLE
Avoiding ZeroDivisionError when calculating rtol in FloatMatcher

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#697]
https://github.com/inducer/relate/blob/90ca3853fdaf33312c36a2a6c8356068bac8e00d/course/page/text.py#L513-L517

When `self.matcher_desc.value ==0`, grade will fail with `ZeroDivisionError`. It should be changed to 
```python
        if hasattr(self.matcher_desc, "rtol"):
            if self.matcher_desc.value != 0:
                if (abs(answer_float - self.matcher_desc.value)
                        / abs(self.matcher_desc.value)
                        > self.matcher_desc.rtol):
                    return 0
            else:
                if (abs(answer_float - self.matcher_desc.value)
                        > self.matcher_desc.rtol):
                    return 0
```

**Comment by inducer** [comment]
https://github.com/inducer/relate/blob/90ca3853fdaf33312c36a2a6c8356068bac8e00d/course/page/text.py#L452-L457

`rtol` isn't allowed when the value is zero.

**Comment by inducer** [comment]
Closing for now, let me know if you think that's wrong.

**Comment by dzhuang** [comment]
Thanks for the explanation. I should have tested it before reporting.
