### ISSUE TITLE
Deprecation warning from Dulwich

### ISSUE THREAD

**Issue by joshuata** [inducer/relate#714]
I am seeing two deprecation warnings when I run the test suite. One is [course/versioning.py:L107](https://github.com/inducer/relate/blob/b8dfc69b7dd0a1e9994f105266ad75aa217200b9/course/versioning.py#L107) and the other is [course/versioning.py:217](https://github.com/inducer/relate/blob/b8dfc69b7dd0a1e9994f105266ad75aa217200b9/course/versioning.py#L217)

Clipped lines:
```
/home/runner/work/relate/relate/course/versioning.py:107: DeprecationWarning: Use FetchPackResult.refs instead.
107
    for ref, sha in remote_refs.items():
...
/home/runner/work/relate/relate/course/versioning.py:217: DeprecationWarning: Use FetchPackResult.refs instead.
123
    new_sha = repo[b"HEAD"] = remote_refs[b"HEAD"]
```

**Comment by inducer** [comment]
#715
