### ISSUE TITLE
Calendar seems not working properly

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#74]
With the [example](http://documen.tician.de/relate/content.html#the-calendear-information-file-events-yml) your provided, alternative title, color and expected hyperlink are not rendered. 

What's more, are students permitted to view the full calendar and the expected links although there's time rule for those content?

**Comment by inducer** [comment]
I am using this functionality all the time, and it seems to be working fine for me. Can you be more specific as to what you're doing, what you are expecting to happen, and what actually happens?

**Comment by dzhuang** [comment]
Sorry, its my fault. The events_file in in my repo is "event.yml", and I set up the course using "events.yml".  Should be fixed in https://github.com/inducer/relate/pull/75.
