### ISSUE TITLE
Inconsistency in description and validator of participation tag name

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#744]
Description: `Format is lower-case-with-hyphens. Do not use spaces.`
Used RegexValidator: `^\w+$` (not allowing hyphens)

**Comment by dzhuang** [comment]
Also, Is it possible to use non-ascii characters?

**Comment by inducer** [comment]
I'd be OK making that `str.isidentifier()`.

**Comment by dzhuang** [comment]
That's a good shortcut for this. Thanks.

> I'd be OK making that str.isidentifier().

**Comment by dzhuang** [comment]
`role.identifier` seems to fall into the same issue.

**Comment by dzhuang** [comment]
Closed via #746
