### ISSUE TITLE
Sandbox failed. 

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#8]
It worked without problems 2 weeks before.

It gives ``Page failed to load/validate: ValidationError: sandbox: flow page has no ID`` when I test the following part:

```
    -
        type: Page
        id: welcome
        content: |

            # Welcome to the test quiz for RELATE!

            Don't be scared.

```

**Comment by inducer** [comment]
You'll need to remove the leading dash.

**Comment by dzhuang** [comment]
Again, my shame! :(

**Comment by inducer** [comment]
No worries. :)
