### ISSUE TITLE
InlineQuestion calls markup_to_html without a PageContext

### ISSUE THREAD

**Issue by inducer** [inducer/relate#80]
@dzhuang 

I just discovered that you don't pass a `PageContext` to `markup_to_html` in InlineQuestion, here for example:

https://github.com/inducer/relate/blob/882803aad9243b8d983bd2a4195ea802c330cb2c/course/page/inline.py#L382

As of 882803a, this breaks caching of rendered markup. (it has to, since markup rendering depends on the course for which it is done). Could you please fix this?

**Comment by dzhuang** [comment]
Yes, you're right. That will cause problems, for example, course specific links and jinja macros won't be rendered correctly.

The reason I did that is, I need to use markup_to_html to validate / get question body and answer items (of each types) in  __init__ of InlineQuestion. However, there's no PageContext in __init__ method.

I will try to fix it.

**Comment by dzhuang** [comment]
I think I know how to fix it. Validation and render should be separated: use vctx in validation and, and use page_context when rendering html. Need sometime to modify and test.

**Comment by dzhuang** [comment]
However, I found images and latex expressions are not rendered correctly in ``ChoicesAnswer`` choices.
