### ISSUE TITLE
Again for offsetting of may-resubmit in flow page

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#84]
Since there are offset settings [here](https://github.com/inducer/relate/blob/93a74f6808ce46307dac40db50adbda68eb764ab/course/templates/course/flow-page.html#L100-L106), if this [line](https://github.com/inducer/relate/commit/03afaf4eafb25e16cef9d4feca31915a73a7f150#diff-7b95f7e2c3ef72b907eb564186ec1552L50) is removed, then the issue fix by 93a74f6808ce46307dac40db50adbda68eb764ab will arise again.

**Comment by inducer** [comment]
I removed all this because it seems unnecessary with `django-crispy-forms>=1.5`. (I.e. all the layouts were right for me without having to muck around with manual offseting.)

**Comment by dzhuang** [comment]
I've also updated to 1.5.1, there's still bad offset for InlineMultiQuestions according to [these](https://github.com/inducer/relate/blob/93a74f6808ce46307dac40db50adbda68eb764ab/course/templates/course/flow-page.html#L100-L106).

**Comment by inducer** [comment]
Looks OK to me:

![bildschirmfoto von 2015-09-15 13-13-24](https://cloud.githubusercontent.com/assets/352067/9885603/a236f30e-5bab-11e5-96e5-fbf782977c69.png)

**Comment by dzhuang** [comment]
Sorry for having not made it clear, when a flow allow change anwer after the answer is submitted.

![relate](https://cloud.githubusercontent.com/assets/7379654/9893162/7511c8fc-5c48-11e5-9ac0-2e183fee531e.png)

**Comment by inducer** [comment]
Oh, argh! You're right.

**Comment by inducer** [comment]
3bdade4 should do it. Sorry for re-breaking this.

**Comment by dzhuang** [comment]
Thank you ! There's no sorry :-)
