### ISSUE TITLE
Videojs issue

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#846]
As of https://github.com/videojs/video.js/blob/main/CHANGELOG.md#7111-2020-12-22, video.js had removed flash since version 7.11.1. The `videojs/dist/video-js/video-js.swf` no longer exists.

https://github.com/inducer/relate/blob/9454c6e7e4895cf13bb6af4929b853b221ca25d2/relate/templates/base.html#L43-L45

**Comment by inducer** [comment]
Thanks for the report! #852 should address that.

**Comment by dzhuang** [comment]
Thanks for the fix.
