### ISSUE TITLE
If the enrollment preapprovements are added after the enrollment requests of students

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#91]
Then the students will still need to wait for the approvement of the tutor.

**Comment by inducer** [comment]
Easy patch here:

https://github.com/inducer/relate/blob/16fe41435c85c413dc97db64e631f046e45f93b3/course/enrollment.py#L261

**Comment by dzhuang** [comment]
Thank you, I tried to fix it in https://github.com/inducer/relate/pull/94.
