### ISSUE TITLE
Not searchable when select user to impersonate

### ISSUE THREAD

**Issue by dzhuang** [inducer/relate#92]

**Comment by inducer** [comment]
https://github.com/applegrew/django-select2 ?

**Comment by dzhuang** [comment]
Seems select2 will do that work, let's wait if you or I have time to improve it.
What's more, if a teacher is the auditor of multiple courses, it's better to allow adding course filter before select user to impersonate. And if a student enrolled in those course, there will be duplicated items in the option list.

**Comment by dzhuang** [comment]
Partly fixed by https://github.com/inducer/relate/pull/106.

**Comment by inducer** [comment]
Why only 'partly'?

**Comment by dzhuang** [comment]
This has not been fixed: If a teacher is the auditor of multiple courses, it's better to allow adding course filter before select user to impersonate. Otherwise,  if a student enrolled in those courses, there will be duplicated items in the option list.

**Comment by dzhuang** [comment]
I think the duplication issue should be fixed by 211168e9052e7966f2f3cc2720a358cb4d5e948c.
