### ISSUE TITLE
Default Git repo no longer works (and won't again)

### ISSUE THREAD

**Issue by davis68** [inducer/relate#920]
![image](https://user-images.githubusercontent.com/5383842/160206789-fb10b68e-88a1-46fa-af72-dc7b414c23d9.png)

The unencrypted `git:` protocol is no longer supported by GitHub, so this will need to either be dropped or moved to a different source.

https://github.blog/2021-09-01-improving-git-protocol-security-github/

**Comment by dzhuang** [comment]
See commit 1efb61d87e322e5782141e6d54fe180d28a69cf9 for tests. i.e., switching to `https://` protocol will work. This is the case if you serve your course material on GitHub.

**Comment by inducer** [comment]
Closing this then. @davis68, if this causes you further grief, do speak up.
